// Generated by scripts/generate-automated-cases.mjs from `jest --coverage` — don't edit by hand.
// Run `pnpm qa:cases` to refresh it.

export type CoverageMetrics = {
  lines: number;
  statements: number;
  functions: number;
  branches: number;
};

export type CoverageGroup = CoverageMetrics & { folder: string; detail: string; files: number };

export const COVERAGE_UPDATED_AT = '2026-10-09';

export const coverage: { total: CoverageMetrics; groups: CoverageGroup[] } = {
  total: { lines: 97.7, statements: 96.7, functions: 96.3, branches: 92.5 },
  groups: [
    {
      folder: 'src/lib',
      detail: 'lógica compartida, seguridad, cache, S3',
      files: 93,
      lines: 97.8,
      statements: 96.7,
      functions: 96.4,
      branches: 92.3,
    },
    {
      folder: 'src/actions',
      detail: 'server actions',
      files: 112,
      lines: 96.6,
      statements: 95.5,
      functions: 96.5,
      branches: 88.5,
    },
    {
      folder: 'src/schemas',
      detail: 'validaciones con zod',
      files: 13,
      lines: 99.6,
      statements: 98.6,
      functions: 100,
      branches: 96.7,
    },
    {
      folder: 'src/hooks',
      detail: 'hooks de React',
      files: 2,
      lines: 100,
      statements: 98.5,
      functions: 100,
      branches: 94.4,
    },
    {
      folder: 'src/components',
      detail: 'componentes',
      files: 424,
      lines: 97.6,
      statements: 96.9,
      functions: 95.6,
      branches: 93,
    },
    {
      folder: 'src/app',
      detail: 'páginas, layouts y route handlers',
      files: 328,
      lines: 98.3,
      statements: 97,
      functions: 97.7,
      branches: 93.4,
    },
  ],
};
