// Generated by scripts/generate-automated-cases.mjs from `jest --coverage` — don't edit by hand.
// Run `pnpm qa:cases` to refresh it.

export type CoverageMetrics = {
  lines: number;
  statements: number;
  functions: number;
  branches: number;
};

export type CoverageGroup = CoverageMetrics & { folder: string; detail: string; files: number };

export const COVERAGE_UPDATED_AT = '2026-10-08';

export const coverage: { total: CoverageMetrics; groups: CoverageGroup[] } = {
  total: { lines: 97.2, statements: 96.4, functions: 96.1, branches: 92.2 },
  groups: [
    {
      folder: 'src/lib',
      detail: 'lógica compartida, seguridad, cache, S3',
      files: 89,
      lines: 97.8,
      statements: 96.7,
      functions: 96.2,
      branches: 92.6,
    },
    {
      folder: 'src/actions',
      detail: 'server actions',
      files: 108,
      lines: 96.4,
      statements: 95.3,
      functions: 96.2,
      branches: 88.5,
    },
    {
      folder: 'src/schemas',
      detail: 'validaciones con zod',
      files: 12,
      lines: 100,
      statements: 99,
      functions: 100,
      branches: 100,
    },
    {
      folder: 'src/hooks',
      detail: 'hooks de React',
      files: 2,
      lines: 100,
      statements: 98.5,
      functions: 100,
      branches: 94.4,
    },
    {
      folder: 'src/components',
      detail: 'componentes',
      files: 415,
      lines: 96.8,
      statements: 96.2,
      functions: 95.5,
      branches: 92.4,
    },
    {
      folder: 'src/app',
      detail: 'páginas, layouts y route handlers',
      files: 320,
      lines: 98.3,
      statements: 97.2,
      functions: 97.6,
      branches: 93.6,
    },
  ],
};
