// Generated by scripts/generate-automated-cases.mjs from `jest --coverage` — don't edit by hand.
// Run `pnpm qa:cases` to refresh it.

export type CoverageMetrics = {
  lines: number;
  statements: number;
  functions: number;
  branches: number;
};

export type CoverageGroup = CoverageMetrics & { folder: string; detail: string; files: number };

export const COVERAGE_UPDATED_AT = '2026-10-04';

export const coverage: { total: CoverageMetrics; groups: CoverageGroup[] } = {
  total: { lines: 99.5, statements: 98.7, functions: 99.1, branches: 95.5 },
  groups: [
    {
      folder: 'src/lib',
      detail: 'lógica compartida, seguridad, cache, S3',
      files: 66,
      lines: 99.7,
      statements: 98.9,
      functions: 100,
      branches: 94.9,
    },
    {
      folder: 'src/actions',
      detail: 'server actions',
      files: 97,
      lines: 99.2,
      statements: 98.4,
      functions: 99.2,
      branches: 93.3,
    },
    {
      folder: 'src/schemas',
      detail: 'validaciones con zod',
      files: 10,
      lines: 100,
      statements: 100,
      functions: 100,
      branches: 100,
    },
    {
      folder: 'src/hooks',
      detail: 'hooks de React',
      files: 2,
      lines: 100,
      statements: 98.5,
      functions: 100,
      branches: 94.4,
    },
    {
      folder: 'src/components',
      detail: 'componentes',
      files: 372,
      lines: 99.3,
      statements: 98.7,
      functions: 98.7,
      branches: 95.4,
    },
    {
      folder: 'src/app',
      detail: 'páginas, layouts y route handlers',
      files: 295,
      lines: 99.9,
      statements: 98.7,
      functions: 99.8,
      branches: 96.6,
    },
  ],
};
