import { screen, within } from '@testing-library/react';
import { renderInPlatform } from '@/test/platform';
import { coverage } from './coverage';
import CalidadPage, { metadata } from './page';
import { automatedCases, layerLabels, manualCases, manualCasesAutomated } from './quality-cases';
import { qualityGates, qualityRoadmap, qualityTools } from './quality-stack';

// The case browser has its own tests; here it only has to receive the measured date.
jest.mock('@/components/desarrollo/quality/test-case-browser', () => ({
  TestCaseBrowser: ({ updatedAt }: { updatedAt: string }) => (
    <div data-testid="test-case-browser">{updatedAt}</div>
  ),
}));

// The case and coverage data are regenerated by `pnpm qa:cases`, so every expectation here is
// derived from the same modules the page reads instead of fixed numbers.
const section = (id: string) => {
  const element = document.getElementById(id);
  expect(element).not.toBeNull();
  return within(element!);
};

const byLayer = (layer: string) => automatedCases.filter((c) => c.automation?.layer === layer);

describe('CalidadPage', () => {
  beforeEach(() => renderInPlatform(<CalidadPage />));

  it('has SEO metadata for /desarrollo/calidad', () => {
    expect(metadata.title).toBe('Quality engineering');
    expect(metadata.openGraph).toMatchObject({
      url: expect.stringMatching(/\/desarrollo\/calidad$/),
    });
  });

  it('counts every manual and automated case in the header', () => {
    expect(
      screen.getByText(
        `quality engineering · ${manualCases.length + automatedCases.length} casos de prueba`,
      ),
    ).toBeInTheDocument();
  });

  it('lists every quality gate with its command', () => {
    const gates = section('enfoque');
    for (const gate of qualityGates) {
      expect(gates.getByText(gate.stage)).toBeInTheDocument();
      expect(gates.getByText(gate.command)).toBeInTheDocument();
    }
    expect(gates.getByText(/archivos de tests automatizados/)).toHaveTextContent(
      `automatizando ${manualCasesAutomated} de los ${manualCases.length} casos`,
    );
  });

  it('splits the automated suite by layer', () => {
    const pyramid = section('piramide');
    for (const [layer, label] of Object.entries(layerLabels)) {
      const tests = byLayer(layer);
      const files = new Set(tests.map((c) => c.automation!.file)).size;
      expect(pyramid.getByText(label).nextSibling).toHaveTextContent(
        `${tests.length} tests · ${files} archivos`,
      );
    }
  });

  it('shows the coverage of every folder and the total', () => {
    const cobertura = section('cobertura');
    for (const group of coverage.groups) {
      const row = cobertura.getByText(group.folder).parentElement!.parentElement!;
      expect(row).toHaveTextContent(`${group.files} archivos`);
      expect(row).toHaveTextContent(`líneas${group.lines}%`);
      expect(row).toHaveTextContent(`ramas${group.branches}%`);
    }
    expect(
      cobertura.getByText(new RegExp(`total: ${coverage.total.lines}% de líneas`)),
    ).toBeInTheDocument();
  });

  it('summarizes the weekly e2e regression', () => {
    const regression = section('regresion');
    expect(regression.getByText('casos manuales automatizados').nextSibling).toHaveTextContent(
      `${manualCasesAutomated}/${manualCases.length}`,
    );
    expect(regression.getByText('tests e2e').nextSibling).toHaveTextContent(
      String(byLayer('e2e').length),
    );
    expect(regression.getByText('integración (Postgres)').nextSibling).toHaveTextContent(
      String(byLayer('integration').length),
    );
  });

  it('links tools to their file on GitHub and marks the roadmap as planned', () => {
    const tool = qualityTools.find((item) => item.file)!;
    expect(section('herramientas').getByRole('link', { name: `${tool.file} ↗` })).toHaveAttribute(
      'href',
      `https://github.com/programaconnosotros/pcn-website/blob/main/${tool.file}`,
    );
    const pending = section('pendiente');
    expect(pending.getAllByText('[ ]')).toHaveLength(qualityRoadmap.length);
  });

  it('hands the case browser the measured date and links back to contributing', () => {
    expect(screen.getByTestId('test-case-browser')).toHaveTextContent(/\d{4}$/);
    expect(screen.getByRole('link', { name: '~/desarrollo#contribuir →' })).toHaveAttribute(
      'href',
      '/desarrollo#contribuir',
    );
  });
});
