export interface Video {
  /** YouTube video id. */
  id: string;
  title: string;
  /** Who presents it, when it differs from the channel that published it. */
  speaker?: string;
  channel: string;
  /** Publication date on YouTube, ISO YYYY-MM-DD. */
  date: string;
  durationSeconds: number;
  /** Conference talks, also listed under "externas" on /charlas. */
  isTalk?: boolean;
}

const allVideos: Video[] = [
  {
    id: 'SlGRN8jh2RI',
    title: 'Why coding is solved, and what comes next',
    speaker: 'Boris Cherny (Anthropic)',
    channel: 'Sequoia Capital',
    date: '2026-05-04',
    durationSeconds: 1476,
    isTalk: true,
  },
  {
    id: '96jN2OCOfLs',
    title: 'From vibe coding to agentic engineering',
    speaker: 'Andrej Karpathy y Stephanie Zhan',
    channel: 'Sequoia Capital',
    date: '2026-04-29',
    durationSeconds: 1789,
    isTalk: true,
  },
  {
    id: 'v4F1gFy-hqg',
    title: 'Software fundamentals matter more than ever',
    speaker: 'Matt Pocock',
    channel: 'AI Engineer',
    date: '2026-04-23',
    durationSeconds: 1106,
    isTalk: true,
  },
  {
    id: '_mi3alkqy4s',
    title: 'The death of the code review: what the data actually says',
    speaker: 'Laurie Voss (Arize AI)',
    channel: 'AI Engineer',
    date: '2026-09-30',
    durationSeconds: 1480,
    isTalk: true,
  },
  {
    id: 'LlgiOCmFG_w',
    title: 'Fixing the PR bottleneck',
    speaker: 'Matt Pocock (AIHero)',
    channel: 'AI Engineer',
    date: '2026-09-25',
    durationSeconds: 1354,
    isTalk: true,
  },
  {
    id: 'WkBPX-oDMnA',
    title: 'Understanding is the new bottleneck',
    speaker: 'Geoffrey Litt (Notion)',
    channel: 'AI Engineer',
    date: '2026-07-10',
    durationSeconds: 1173,
    isTalk: true,
  },
  {
    id: 'xUnRQ9vLXxo',
    title: 'Everything we knew about software has changed',
    speaker: 'Theo Browne (t3.gg)',
    channel: 'AI Engineer',
    date: '2026-07-08',
    durationSeconds: 961,
    isTalk: true,
  },
  {
    id: 'tUPPVhBBcoM',
    title: 'Software engineering is becoming factory engineering',
    speaker: 'Zach Lloyd (Warp)',
    channel: 'AI Engineer',
    date: '2026-09-27',
    durationSeconds: 1236,
    isTalk: true,
  },
  {
    id: 'vGCJ7diEtrw',
    title: 'What it actually takes to build a software factory',
    speaker: 'Tereza Tížková (Factory)',
    channel: 'AI Engineer',
    date: '2026-09-27',
    durationSeconds: 1369,
    isTalk: true,
  },
  {
    id: 'iRGc8KQDyQ8',
    title: 'Composition, caching, and architecture in modern Next.js',
    speaker: 'Aurora Scharff (Crayon Consulting)',
    channel: 'Vercel',
    date: '2025-12-03',
    durationSeconds: 1787,
    isTalk: true,
  },
  {
    id: 'WT7_TJS0tFE',
    title: 'Next.js for AI agents',
    speaker: 'Jude Gao (Vercel)',
    channel: 'Vercel',
    date: '2025-11-17',
    durationSeconds: 1542,
    isTalk: true,
  },
  {
    id: 'f--3aG0XfCw',
    title: 'Next.js at the speed of Bun',
    speaker: 'Lydia Hallie (Bun)',
    channel: 'Vercel',
    date: '2025-12-15',
    durationSeconds: 1131,
    isTalk: true,
  },
  {
    id: 'gcwzWzC7gUA',
    title: 'Rails World 2025 Opening Keynote',
    speaker: 'DHH',
    channel: 'Ruby on Rails',
    date: '2025-09-04',
    durationSeconds: 3835,
    isTalk: true,
  },
  {
    id: 'vDjW_dRyKXY',
    title: 'Rails World 2026 Opening Keynote',
    speaker: 'DHH',
    channel: 'Ruby on Rails',
    date: '2026-09-23',
    durationSeconds: 3787,
    isTalk: true,
  },
  {
    id: 'jjheLyrTG4Y',
    title: 'El futuro para los devs',
    speaker: 'Miguel Ángel Durán García (midudev)',
    channel: 'Nerdearla',
    date: '2026-09-26',
    durationSeconds: 2618,
    isTalk: true,
  },
  {
    id: 'Pu8JPkVvMjQ',
    title: 'Por qué el open source lanza carreras (y cómo empezar hoy)',
    speaker: 'Stormy Peters (AWS)',
    channel: 'Nerdearla',
    date: '2026-10-01',
    durationSeconds: 2131,
    isTalk: true,
  },
  {
    id: 'xrM1g9m_phQ',
    title: 'Building open source teams',
    speaker: 'Bruce Momjian (PostgreSQL)',
    channel: 'Nerdearla',
    date: '2026-10-01',
    durationSeconds: 2063,
    isTalk: true,
  },
  {
    id: 'wga8Joa_8eQ',
    title: 'Open source in the age of AI',
    speaker: 'Peter Zaitsev (Percona)',
    channel: 'Nerdearla',
    date: '2026-10-01',
    durationSeconds: 1775,
    isTalk: true,
  },
  {
    id: 'IPTQJoK3ij0',
    title: 'An AI that you should be using more',
    speaker: 'D. Richard Hipp (SQLite)',
    channel: 'Nerdearla',
    date: '2026-10-01',
    durationSeconds: 1792,
    isTalk: true,
  },
  {
    id: '1CkA4a93LMg',
    title: 'The future of building with AI: multimodal agents, generative media, and open models',
    speaker: 'Omar Sanseviero (Google DeepMind)',
    channel: 'Nerdearla',
    date: '2026-10-01',
    durationSeconds: 2182,
    isTalk: true,
  },
  {
    id: 'VHXFUyzlFIM',
    title: 'Panel: Getting started in open source development',
    speaker: 'Anna Widenius, Hilary Carter, Megan Knight, Stormy Peters y Leandro Colombo Viña',
    channel: 'Nerdearla',
    date: '2026-10-01',
    durationSeconds: 4970,
    isTalk: true,
  },
  {
    id: 'X-Y3echy_aE',
    title: 'Panel: The philosophy and power of open source leadership',
    speaker:
      'D. Richard Hipp, Jean-Baptiste Kempf, Madelyn Olson, Monty Widenius, Robin Bender Ginn, Roger Dingledine y Leandro Colombo Viña',
    channel: 'Nerdearla',
    date: '2026-10-01',
    durationSeconds: 5291,
    isTalk: true,
  },
  {
    id: 'iqSXHICWa1Y',
    title: 'Cuando mi agente perdió la paciencia: seguridad en IA',
    speaker: 'Pablo Fredrikson (Bitso)',
    channel: 'Nerdearla',
    date: '2026-09-28',
    durationSeconds: 1973,
    isTalk: true,
  },
  {
    id: 'aH8zW8jGak0',
    title: 'Estamos mergeando código que nadie entiende',
    speaker: 'Juan Pablo Flores (CodeRabbit)',
    channel: 'Nerdearla',
    date: '2026-09-28',
    durationSeconds: 2080,
    isTalk: true,
  },
  {
    id: '-QWY3WX_nN8',
    title: 'Millones mirando el mismo partido. Millones de desafíos detrás.',
    speaker: 'Lucas Freije y León Pérez (Personal)',
    channel: 'Nerdearla',
    date: '2026-09-28',
    durationSeconds: 2133,
    isTalk: true,
  },
  {
    id: 'AJOGzVygGcY',
    title: "What's new in React 19",
    speaker: 'Lydia Hallie',
    channel: 'React Conf',
    date: '2024-07-25',
    durationSeconds: 1203,
    isTalk: true,
  },
  {
    id: 'SqVLqvsiAYQ',
    title: 'Performance in React and Next.js',
    speaker: 'Lydia Hallie',
    channel: 'Vercel',
    date: '2023-11-03',
    durationSeconds: 971,
    isTalk: true,
  },
  {
    id: 'gfU1iZnjRZM',
    title: 'Next.js Conf Keynote (Next.js 14)',
    speaker: 'Guillermo Rauch (Vercel)',
    channel: 'Vercel',
    date: '2023-11-03',
    durationSeconds: 1741,
    isTalk: true,
  },
  {
    id: 'qpczQVJMG1Y',
    title: 'Type-safe URL state in Next.js with nuqs',
    speaker: 'François Best (nuqs)',
    channel: 'Vercel',
    date: '2025-11-13',
    durationSeconds: 1509,
    isTalk: true,
  },
  {
    id: 'd-hvEqWb79c',
    title: 'Reactive state for the backend',
    speaker: 'Rhys Sullivan (Vercel)',
    channel: 'Vercel',
    date: '2025-11-24',
    durationSeconds: 854,
    isTalk: true,
  },
  {
    id: 'PN1HgvAOmi8',
    title: 'Advanced rendering patterns',
    speaker: 'Lydia Hallie',
    channel: 'Real World React',
    date: '2022-05-24',
    durationSeconds: 1189,
    isTalk: true,
  },
  {
    id: 'Mh_mztkapYU',
    title: 'Back to the basics: modelando nuestro dominio',
    speaker: 'Javier Ferrer y Rafa Gómez (CodelyTV)',
    channel: 'Software Crafters Barcelona',
    date: '2020-02-02',
    durationSeconds: 3280,
    isTalk: true,
  },
  {
    id: '8_h6ULJMR3k',
    title: 'Clean Code, SOLID, CQRS, DDD, ¿y qué hay de nuestros tests?',
    speaker: 'Rafa Gómez y Javier Ferrer (CodelyTV)',
    channel: 'Software Crafters Barcelona',
    date: '2019-02-19',
    durationSeconds: 3475,
    isTalk: true,
  },
  {
    id: 'o0w-jYun6AU',
    title: 'De código acoplado al framework hasta microservicios pasando por DDD',
    speaker: 'Javier Ferrer y Rafa Gómez (CodelyTV)',
    channel: 'CodelyTV',
    date: '2016-11-21',
    durationSeconds: 2949,
    isTalk: true,
  },
  {
    id: 'MJUJ4wbFm_A',
    title: 'An introduction to Git and GitHub',
    speaker: 'Brian Yu (Harvard)',
    channel: 'CS50',
    date: '2016-11-10',
    durationSeconds: 2307,
    isTalk: true,
  },
  {
    id: 'V6VP-2aIcSc',
    title: 'Object-oriented programming is garbage: 3800 SLOC example',
    channel: 'Brian Will',
    date: '2016-03-21',
    durationSeconds: 3168,
    isTalk: true,
  },
  {
    id: 'o_TH-Y78tt4',
    title: 'The principles of clean architecture',
    speaker: 'Robert C. Martin (Uncle Bob)',
    channel: 'NorfolkDevelopers',
    date: '2015-12-15',
    durationSeconds: 4403,
    isTalk: true,
  },
  {
    id: 'DngAZyWMGR0',
    title: 'Making architecture matter',
    speaker: 'Martin Fowler (Thoughtworks)',
    channel: "O'Reilly",
    date: '2015-07-23',
    durationSeconds: 844,
    isTalk: true,
  },
  {
    id: 'TMuno5RZNeE',
    title: 'SOLID principles of object oriented and agile design',
    speaker: 'Robert C. Martin (Uncle Bob)',
    channel: 'People career',
    date: '2015-05-23',
    durationSeconds: 5015,
    isTalk: true,
  },
  {
    id: '76rR68ktQvo',
    title: 'DHH: How to build a profitable company without losing control',
    speaker: 'DHH y David Senra',
    channel: 'David Senra',
    date: '2026-07-26',
    durationSeconds: 6099,
  },
  {
    id: 'LU6K07U4wOk',
    title: 'Jev de TypeSafe AI: el modelo que NO escribe texto',
    channel: 'Fazt',
    date: '2026-09-18',
    durationSeconds: 1850,
  },
  {
    id: 'NYFGCESmikA',
    title: 'DHH: Future of programming, AI, agentic engineering, vibe coding & Linux',
    speaker: 'DHH y Lex Fridman',
    channel: 'Lex Fridman',
    date: '2026-08-26',
    durationSeconds: 18951,
  },
  {
    id: 'vagyIcmIGOQ',
    title: 'DHH: Future of programming, AI, Ruby on Rails, productivity & parenting',
    speaker: 'DHH y Lex Fridman',
    channel: 'Lex Fridman',
    date: '2025-07-12',
    durationSeconds: 22128,
  },
  {
    id: 'eiC58R16hb8',
    title: 'JavaScript Visualized - Event Loop, Web APIs, (Micro)task Queue',
    channel: 'Lydia Hallie',
    date: '2024-04-04',
    durationSeconds: 754,
  },
  {
    id: 'hJHvdBlSxug',
    title: 'How The Web Works - The Big Picture',
    channel: 'Academind',
    date: '2019-04-15',
    durationSeconds: 745,
  },
  {
    id: 'xckH5s3UuX4',
    title: 'Understanding the V8 JavaScript Engine',
    channel: 'freeCodeCamp Talks',
    date: '2020-12-22',
    durationSeconds: 644,
  },
  {
    id: '6ERUGFurDHY',
    title: 'Intent-driven development with Claude Code & Fable 5',
    channel: 'Google Cloud Tech',
    date: '2026-07-06',
    durationSeconds: 2761,
  },
  {
    id: 'q9Vaoz0hd0U',
    title: '¿Qué es esto del Harness Engineering?',
    channel: 'BettaTech',
    date: '2026-04-29',
    durationSeconds: 1515,
  },
  {
    id: 'FhQfG-Q4wL4',
    title: 'Yo no entendía AWS hasta ver esto',
    channel: 'BettaTech',
    date: '2026-09-13',
    durationSeconds: 1239,
  },
  {
    id: 'lBimeKh88OU',
    title: 'Dame 30 minutos y te enseño a implementar un RAG con embeddings',
    channel: 'BettaTech',
    date: '2026-08-02',
    durationSeconds: 1836,
  },
  {
    id: '2myd3cgqe2k',
    title: '¿Qué es esto del Graph Engineering?',
    channel: 'BettaTech',
    date: '2026-07-29',
    durationSeconds: 1107,
  },
  {
    id: 'RBzGXBYa0Lg',
    title: '4 patrones agénticos que deberías conocer',
    channel: 'BettaTech',
    date: '2026-07-26',
    durationSeconds: 1485,
  },
  {
    id: '18FeGXyB-sI',
    title: '¿Qué es esto del Loop Engineering?',
    channel: 'BettaTech',
    date: '2026-06-14',
    durationSeconds: 577,
  },
  {
    id: '2nEiIG-xca4',
    title: 'Todo lo que necesitás saber sobre diseño de sistemas en 24 minutos',
    channel: 'BettaTech',
    date: '2026-06-28',
    durationSeconds: 1423,
  },
  {
    id: 'PoXC6XcVa1M',
    title: 'Implemento el sistema de agentes de Uncle Bob, te lo muestro',
    channel: 'BettaTech',
    date: '2026-06-03',
    durationSeconds: 1347,
  },
  {
    id: 'ElGlTv2A_bM',
    title: 'Esto es lo que aprendí adaptando Claude Code para SDD',
    channel: 'BettaTech',
    date: '2026-05-13',
    durationSeconds: 1712,
  },
  {
    id: 'UTNbLoZCOgM',
    title: 'Todo lo que necesitás saber de DevOps en 20 minutos',
    channel: 'BettaTech',
    date: '2026-04-12',
    durationSeconds: 1180,
  },
  {
    id: 'Rla0IMxIlNc',
    title: 'Todo lo que necesitás saber del desarrollo frontend en 19 minutos',
    channel: 'BettaTech',
    date: '2026-03-11',
    durationSeconds: 1127,
  },
  {
    id: 'l3HJsXA-Fa4',
    title: 'Todo lo que necesitás saber del desarrollo backend en 29 minutos',
    channel: 'BettaTech',
    date: '2026-02-05',
    durationSeconds: 1746,
  },
];

/** Every video, newest first. */
export const videos = [...allVideos].sort((a, b) => b.date.localeCompare(a.date));

/** Talks from other conferences the community recommends, newest first. */
export const externalTalks = videos.filter((video) => video.isTalk);

/** Videos that are not conference talks, so they never repeat what `externalTalks` lists. */
export const otherVideos = videos.filter((video) => !video.isTalk);
