import type { Language } from '@/components/ui/language-filter';

export interface Article {
  id: string;
  title: string;
  author: string;
  /** Other people who signed the article with `author`. */
  coauthors?: string[];
  source: string;
  category: string;
  description: string;
  url: string;
  avatar: string;
  date: string; // ISO YYYY-MM-DD
  language: Language;
}

const allArticles: Article[] = [
  {
    id: '1',
    title: 'Loop Engineering',
    author: 'Addy Osmani',
    source: 'addyosmani.com',
    category: 'Programación',
    description:
      'Loop engineering reemplaza los prompts manuales con sistemas autónomos que iteran hasta completar objetivos, cambiando cómo trabajamos con agentes de código.',
    url: 'https://addyosmani.com/blog/loop-engineering/',
    avatar: 'https://github.com/addyosmani.png?size=128',
    date: '2026-06-07',
    language: 'en',
  },
  {
    id: '2',
    title: 'Agent Harness Engineering',
    author: 'Addy Osmani',
    source: 'addyosmani.com',
    category: 'Programación',
    description:
      'Explora cómo la arquitectura que rodea a un modelo de IA (el "harness") es tan importante como el modelo mismo para construir agentes de código efectivos.',
    url: 'https://addyosmani.com/blog/agent-harness-engineering/',
    avatar: 'https://github.com/addyosmani.png?size=128',
    date: '2026-04-19',
    language: 'en',
  },
  {
    id: '3',
    title: 'Agentic Infrastructure',
    author: 'Tom Occhino',
    source: 'vercel.com',
    category: 'Arquitectura',
    description:
      'La infraestructura agéntica permite que agentes de IA desplieguen, construyan y ejecuten software de forma autónoma, transformando cómo operan los sistemas modernos.',
    url: 'https://vercel.com/blog/agentic-infrastructure',
    avatar: 'https://github.com/tomocchino.png?size=128',
    date: '2026-04-09',
    language: 'en',
  },
  {
    id: '4',
    title: "Don't Outsource the Learning",
    author: 'Addy Osmani',
    source: 'addyosmani.com',
    category: 'Programación',
    description:
      'Delegar tareas a la IA sin aprender activamente genera deuda cognitiva: se gana velocidad a corto plazo pero se erosiona la comprensión profunda necesaria para crecer como ingeniero.',
    url: 'https://addyosmani.com/blog/dont-outsource-learning/',
    avatar: 'https://github.com/addyosmani.png?size=128',
    date: '2026-05-16',
    language: 'en',
  },
  {
    id: '5',
    title: 'handoff: Move Context Between Agent Sessions',
    author: 'Matt Pocock',
    source: 'aihero.dev',
    category: 'Programación',
    description:
      'Skill que permite trasladar solo el contexto relevante de una sesión de agente a otra, manteniendo cada sesión enfocada y evitando la contaminación de contexto.',
    url: 'https://www.aihero.dev/skills-handoff',
    avatar: 'https://github.com/mattpocock.png?size=128',
    date: '2026-05-13',
    language: 'en',
  },
  {
    id: '6',
    title: 'Agent Skills',
    author: 'Addy Osmani',
    source: 'addyosmani.com',
    category: 'Programación',
    description:
      'Un conjunto de workflows que cubren las fases del ciclo de vida del software (Define, Plan, Build, Verify, Review, Ship) para que los agentes de código no salteen las prácticas de ingeniería que aseguran calidad.',
    url: 'https://addyosmani.com/blog/agent-skills/',
    avatar: 'https://github.com/addyosmani.png?size=128',
    date: '2026-05-03',
    language: 'en',
  },
  {
    id: '7',
    title: 'tdd: Red, Green, Refactor for Agentic Coding',
    author: 'Matt Pocock',
    source: 'aihero.dev',
    category: 'Programación',
    description:
      'Skill que guía a un agente de código por el ciclo red-green-refactor del TDD, verificando comportamiento a través de interfaces públicas en lugar de detalles de implementación.',
    url: 'https://www.aihero.dev/skills-tdd',
    avatar: 'https://github.com/mattpocock.png?size=128',
    date: '2026-04-27',
    language: 'en',
  },
  {
    id: '8',
    title: 'My 7 Phases Of AI Development',
    author: 'Matt Pocock',
    source: 'aihero.dev',
    category: 'Programación',
    description:
      'Un framework de siete fases (idea, investigación, prototipo, PRD, planificación, ejecución y QA) que describe el patrón común en workflows exitosos de desarrollo asistido por IA.',
    url: 'https://www.aihero.dev/my-7-phases-of-ai-development',
    avatar: 'https://github.com/mattpocock.png?size=128',
    date: '2026-03-16',
    language: 'en',
  },
  {
    id: '9',
    title: 'Comprehension Debt',
    author: 'Addy Osmani',
    source: 'addyosmani.com',
    category: 'Programación',
    description:
      'La IA genera código más rápido de lo que los ingenieros pueden comprenderlo, creando una "deuda de comprensión" que las métricas tradicionales no capturan y que puede tener graves consecuencias.',
    url: 'https://addyosmani.com/blog/comprehension-debt/',
    avatar: 'https://github.com/addyosmani.png?size=128',
    date: '2026-03-14',
    language: 'en',
  },
  {
    id: '10',
    title: 'The Factory Model',
    author: 'Addy Osmani',
    source: 'addyosmani.com',
    category: 'Arquitectura',
    description:
      'Los agentes de código representan un cambio de abstracción: el desarrollador ya no escribe código directamente sino que orquesta sistemas que lo generan, elevando el pensamiento sistémico y el juicio arquitectónico.',
    url: 'https://addyosmani.com/blog/factory-model/',
    avatar: 'https://github.com/addyosmani.png?size=128',
    date: '2026-02-25',
    language: 'en',
  },
  {
    id: '11',
    title: 'Agent-native Architectures',
    author: 'Every',
    source: 'every.to',
    category: 'Arquitectura',
    description:
      'Una guía para construir aplicaciones donde los agentes son ciudadanos de primera clase, cubriendo los patrones de diseño que hacen que los sistemas funcionen de forma confiable con IA autónoma.',
    url: 'https://every.to/guides/agent-native',
    avatar: 'https://github.com/everyinc.png?size=128',
    date: '2026-01-17',
    language: 'en',
  },
  {
    id: '12',
    title: 'The Next Two Years of Software Engineering',
    author: 'Addy Osmani',
    source: 'addyosmani.com',
    category: 'Programación',
    description:
      'Una visión de cómo la IA transformará la ingeniería de software en los próximos dos años: nuevos roles, nuevas habilidades críticas y qué fundamentos seguirán siendo irremplazables.',
    url: 'https://addyosmani.com/blog/next-two-years/',
    avatar: 'https://github.com/addyosmani.png?size=128',
    date: '2026-01-05',
    language: 'en',
  },
  {
    id: '13',
    title: 'The golden rules of agent-first product engineering',
    author: 'Jina Yoon',
    source: 'posthog.com',
    category: 'Producto',
    description:
      'Cinco principios para construir productos donde los agentes de IA son la interfaz principal y no un agregado, basados en cómo PostHog reconstruyó su arquitectura de IA dos veces.',
    url: 'https://newsletter.posthog.com/p/the-golden-rules-of-agent-first-product',
    avatar: 'https://github.com/jinayoon.png?size=128',
    date: '2026-04-08',
    language: 'en',
  },
  {
    id: '14',
    title: '24 tips for giving S-tier demos',
    author: 'Jina Yoon',
    source: 'posthog.com',
    category: 'Producto',
    description:
      '24 consejos prácticos para dar demos memorables —estructura, narrativa, preparación y creatividad— que pueden definir si un proyecto o startup despega.',
    url: 'https://newsletter.posthog.com/p/how-to-demo',
    avatar: 'https://github.com/jinayoon.png?size=128',
    date: '2026-05-28',
    language: 'en',
  },
  {
    id: '15',
    title: 'Great companies are built in hackathons',
    author: 'Ian Vanagas',
    source: 'posthog.com',
    category: 'Producto',
    description:
      'Por qué las hackathons, bien estructuradas, son motores de innovación: separarlas del trabajo diario, incluir a todos, exigir demos y dejar enviar a producción lo que funciona.',
    url: 'https://newsletter.posthog.com/p/great-companies-are-built-in-hackathons',
    avatar: 'https://github.com/ivanagas.png?size=128',
    date: '2026-04-21',
    language: 'en',
  },
  {
    id: '16',
    title: 'WTF does a product manager do? (and why engineers should care)',
    author: 'Jina Yoon',
    source: 'posthog.com',
    category: 'Producto',
    description:
      'Tres habilidades clave de product management que todo ingeniero debería adoptar: reunir contexto, crear loops de feedback y comunicar decisiones de forma accionable.',
    url: 'https://newsletter.posthog.com/p/an-engineers-guide-to-product-management',
    avatar: 'https://github.com/jinayoon.png?size=128',
    date: '2026-03-11',
    language: 'en',
  },
  {
    id: '17',
    title: 'Landing Page Hot Tips',
    author: 'Rob Hope',
    source: 'landingpagehottips.com',
    category: 'Diseño',
    description:
      '100 tips digeribles para mejorar tus landing pages: diseño, copywriting, optimización de conversión y experiencia de usuario, con ejemplos prácticos.',
    url: 'https://landingpagehottips.com/',
    avatar: 'https://github.com/robhope.png?size=128',
    date: '2026-06-11',
    language: 'en',
  },
  {
    id: '18',
    title: 'Micro Frontends',
    author: 'Cam Jackson',
    source: 'martinfowler.com',
    category: 'Arquitectura',
    description:
      'Extiende las ideas de los microservicios al frontend: aplicaciones independientes y desplegables por separado que se componen en una sola interfaz, permitiendo que cada equipo trabaje de forma autónoma sin perder una experiencia de usuario cohesiva.',
    url: 'https://martinfowler.com/articles/micro-frontends.html',
    avatar: '/lectura/cam-jackson.jpg',
    date: '2019-06-19',
    language: 'en',
  },
  {
    id: '19',
    title: 'Serverless Architectures',
    author: 'Mike Roberts',
    source: 'martinfowler.com',
    category: 'Arquitectura',
    description:
      'Una guía profunda sobre arquitecturas serverless basadas en Backend as a Service (BaaS) y Functions as a Service (FaaS): sus beneficios, como menor costo operativo y escalado automático, y sus desventajas, como el vendor lock-in.',
    url: 'https://martinfowler.com/articles/serverless.html',
    avatar: '/lectura/mike-roberts.jpg',
    date: '2018-05-22',
    language: 'en',
  },
  {
    id: '20',
    title: 'Feature Toggles (aka Feature Flags)',
    author: 'Pete Hodgson',
    source: 'martinfowler.com',
    category: 'Programación',
    description:
      'Una guía completa sobre feature toggles (feature flags): cómo modificar el comportamiento del sistema sin cambiar código, las distintas categorías de toggles, técnicas de implementación y buenas prácticas para mantenerlos en el tiempo.',
    url: 'https://martinfowler.com/articles/feature-toggles.html',
    avatar: '/lectura/pete-hodgson.png',
    date: '2017-10-09',
    language: 'en',
  },
  {
    id: '21',
    title: 'Brownfield Agentic Engineering',
    author: 'Addy Osmani',
    source: 'addyosmani.com',
    category: 'Programación',
    description:
      'Qué hace falta para que los agentes de código trabajen bien en un codebase más viejo que el propio equipo: contexto heredado, convenciones implícitas y cambios seguros sobre sistemas legacy.',
    url: 'https://addyosmani.com/blog/brownfield-agentic-engineering/',
    avatar: 'https://github.com/addyosmani.png?size=128',
    date: '2026-09-14',
    language: 'en',
  },
  {
    id: '22',
    title: 'Audit your Agent Files',
    author: 'Addy Osmani',
    source: 'addyosmani.com',
    category: 'Programación',
    description:
      'Una guía práctica para auditar los archivos de instrucciones de tu agente (AGENTS.md, CLAUDE.md, skills) y quedarte solo con lo que todavía necesita.',
    url: 'https://addyosmani.com/blog/audit-your-agent-files/',
    avatar: 'https://github.com/addyosmani.png?size=128',
    date: '2026-08-27',
    language: 'en',
  },
  {
    id: '23',
    title: 'Agentic Skill Decay',
    author: 'Addy Osmani',
    source: 'addyosmani.com',
    category: 'Programación',
    description:
      'Los agentes pueden terminar la tarea sin enseñarte nada. Construir experiencia ahora tiene que ser algo deliberado para no perder habilidades con el tiempo.',
    url: 'https://addyosmani.com/blog/agentic-skill-decay/',
    avatar: 'https://github.com/addyosmani.png?size=128',
    date: '2026-08-31',
    language: 'en',
  },
  {
    id: '24',
    title: "Human Judgment Doesn't Leave the Software Factory. It Relocates.",
    author: 'Addy Osmani',
    source: 'addyosmani.com',
    category: 'Arquitectura',
    description:
      'Una guía de campo para construir una software factory que siga teniendo dueño: el criterio humano no desaparece, se muda a otros puntos del proceso.',
    url: 'https://addyosmani.com/blog/human-judgment-doesnt-leave-the-software/',
    avatar: 'https://github.com/addyosmani.png?size=128',
    date: '2026-08-21',
    language: 'en',
  },
  {
    id: '25',
    title: 'Practical Loop Engineering',
    author: 'Addy Osmani',
    source: 'addyosmani.com',
    category: 'Programación',
    description:
      'Objetivos, loops y la disciplina de no delegar tu criterio: cómo aplicar loop engineering en el día a día con agentes de código.',
    url: 'https://addyosmani.com/blog/practical-loop-engineering/',
    avatar: 'https://github.com/addyosmani.png?size=128',
    date: '2026-08-14',
    language: 'en',
  },
  {
    id: '26',
    title: 'Agentic Code Quality',
    author: 'Addy Osmani',
    source: 'addyosmani.com',
    category: 'Programación',
    description:
      'La calidad del código ahora depende de las restricciones que pongas alrededor de tus agentes: tests, linters, revisiones y límites claros.',
    url: 'https://addyosmani.com/blog/agentic-code-quality/',
    avatar: 'https://github.com/addyosmani.png?size=128',
    date: '2026-08-08',
    language: 'en',
  },
  {
    id: '27',
    title: 'Software Factories, Light and Dark',
    author: 'Addy Osmani',
    source: 'addyosmani.com',
    category: 'Arquitectura',
    description:
      'Una software factory es usar loops a escala: el sistema que construye tu software en lugar de vos. Puede correr con humanos en el loop (light) o sin ellos (dark).',
    url: 'https://addyosmani.com/blog/software-factories/',
    avatar: 'https://github.com/addyosmani.png?size=128',
    date: '2026-07-20',
    language: 'en',
  },
  {
    id: '28',
    title: 'Own the Outer Loop',
    author: 'Addy Osmani',
    source: 'addyosmani.com',
    category: 'Programación',
    description:
      "Versión escrita del keynote de cierre del AI Engineer World's Fair 2026: los ingenieros tienen que ser dueños del outer loop, la responsabilidad sobre calidad y verificación de estos sistemas.",
    url: 'https://addyosmani.com/blog/own-the-outer-loop/',
    avatar: 'https://github.com/addyosmani.png?size=128',
    date: '2026-07-15',
    language: 'en',
  },
  {
    id: '29',
    title: 'Earning Taste and Judgment',
    author: 'Addy Osmani',
    source: 'addyosmani.com',
    category: 'Carrera',
    description:
      'El buen criterio solía ser un subproducto de la práctica, pero los agentes se quedaron con esa práctica. Si sos junior, ahora tenés que salir a buscar el criterio a propósito.',
    url: 'https://addyosmani.com/blog/earning-judgment/',
    avatar: 'https://github.com/addyosmani.png?size=128',
    date: '2026-07-14',
    language: 'en',
  },
  {
    id: '30',
    title: 'The Agent-Era Career',
    author: 'Addy Osmani',
    source: 'addyosmani.com',
    category: 'Carrera',
    description:
      'La IA se vuelve buena en todo lo que tiene una respuesta correcta. Tu carrera es todo lo que no la tiene: consejos para crecer profesionalmente en la era de los agentes.',
    url: 'https://addyosmani.com/blog/career-advice-age-of-agents/',
    avatar: 'https://github.com/addyosmani.png?size=128',
    date: '2026-07-06',
    language: 'en',
  },
  {
    id: '31',
    title: 'Agentic Autonomy Levels',
    author: 'Addy Osmani',
    source: 'addyosmani.com',
    category: 'Programación',
    description:
      'La autonomía de los agentes no es una sola escalera sino dos ejes (agencia y orquestación) y seis niveles: un marco para pasar de hacer prompts a operar agentes.',
    url: 'https://addyosmani.com/blog/agentic-autonomy-levels/',
    avatar: 'https://github.com/addyosmani.png?size=128',
    date: '2026-07-02',
    language: 'en',
  },
  {
    id: '32',
    title: 'The New Software Lifecycle',
    author: 'Addy Osmani',
    source: 'addyosmani.com',
    category: 'Producto',
    description:
      'Las ideas clave de un whitepaper de Google sobre cómo la IA está cambiando el ciclo de vida del software, desde el vibe coding hasta la ingeniería agéntica.',
    url: 'https://addyosmani.com/blog/new-sdlc-vibe-coding/',
    avatar: 'https://github.com/addyosmani.png?size=128',
    date: '2026-06-16',
    language: 'en',
  },
  {
    id: '33',
    title: 'Agentic Code Review',
    author: 'Addy Osmani',
    source: 'addyosmani.com',
    category: 'Programación',
    description:
      'Los agentes escriben código cada vez mejor, así que lo difícil de la ingeniería pasó de escribir código a revisarlo. Cómo hacer code review en la era de los agentes.',
    url: 'https://addyosmani.com/blog/agentic-code-review/',
    avatar: 'https://github.com/addyosmani.png?size=128',
    date: '2026-06-15',
    language: 'en',
  },
  {
    id: '34',
    title: 'Composable Architecture Decisions That Matter in 2026',
    author: 'Vercel',
    source: 'vercel.com',
    category: 'Arquitectura',
    description:
      'La arquitectura composable es un problema de ubicación: desacoplar el frontend del backend es fácil, lo difícil es el costo operativo del sistema distribuido que queda debajo y cómo reducirlo.',
    url: 'https://vercel.com/i/composable-architecture-integration-tax',
    avatar: 'https://github.com/vercel.png?size=128',
    date: '2026-07-22',
    language: 'en',
  },
  {
    id: '35',
    title: 'Vector vs Graph Databases: How to Choose for Retrieval Problems',
    author: 'Anshuman Bhardwaj',
    source: 'vercel.com',
    category: 'Arquitectura',
    description:
      'Las bases de datos vectoriales y de grafos recuperan información de forma distinta: búsqueda por similitud versus recorrido de relaciones. Cómo elegir la adecuada según tu problema.',
    url: 'https://vercel.com/i/vector-vs-graph-databases',
    avatar: '/lectura/anshuman-bhardwaj.webp',
    date: '2026-07-10',
    language: 'en',
  },
  {
    id: '36',
    title: 'How to Implement the Backend for Frontend Pattern in 7 Steps',
    author: 'Anshuman Bhardwaj',
    source: 'vercel.com',
    category: 'Arquitectura',
    description:
      'La mayoría de los servicios llamados BFF son en realidad reverse proxies. Un framework de 7 pasos para implementar el patrón backend for frontend cuando realmente aporta valor.',
    url: 'https://vercel.com/i/backend-for-frontend-pattern',
    avatar: '/lectura/anshuman-bhardwaj.webp',
    date: '2026-07-09',
    language: 'en',
  },
  {
    id: '37',
    title: 'GraphQL vs REST: Key Differences and How to Choose',
    author: 'Anshuman Bhardwaj',
    source: 'vercel.com',
    category: 'Arquitectura',
    description:
      'Comparación entre GraphQL y REST en caching, schema, manejo de errores y seguridad, y cómo decidir cuál conviene según lo que tus frontends necesitan del backend.',
    url: 'https://vercel.com/i/graphql-vs-rest',
    avatar: '/lectura/anshuman-bhardwaj.webp',
    date: '2026-07-07',
    language: 'en',
  },
  {
    id: '38',
    title: 'Monolithic vs Microservices: How to Pick the Right Architecture',
    author: 'Ben Sabic',
    source: 'vercel.com',
    category: 'Arquitectura',
    description:
      'Monolito y microservicios comparados en escalado, despliegue, performance y encaje con el equipo, con pasos concretos para migrar de una arquitectura a otra.',
    url: 'https://vercel.com/i/monolithic-vs-microservices',
    avatar: '/lectura/ben-sabic.jpg',
    date: '2026-07-06',
    language: 'en',
  },
  {
    id: '39',
    title: "REST API vs RESTful API: What's the Difference?",
    author: 'Anshuman Bhardwaj',
    source: 'vercel.com',
    category: 'Programación',
    description:
      'REST es el estilo arquitectónico; RESTful es qué tan fielmente una API lo sigue. Dónde se diferencian y cómo construir APIs orientadas a recursos.',
    url: 'https://vercel.com/i/rest-api-vs-restful-api',
    avatar: '/lectura/anshuman-bhardwaj.webp',
    date: '2026-07-02',
    language: 'en',
  },
  {
    id: '40',
    title: 'What Is a CI/CD Pipeline? A Complete Guide',
    author: 'Anshuman Bhardwaj',
    source: 'vercel.com',
    category: 'Programación',
    description:
      'Cómo funcionan los pipelines de integración y entrega continua, las etapas que todo pipeline sigue y cómo armar uno para tu equipo.',
    url: 'https://vercel.com/i/ci-cd-pipeline',
    avatar: '/lectura/anshuman-bhardwaj.webp',
    date: '2026-05-26',
    language: 'en',
  },
  {
    id: '41',
    title: 'When to Run a Self-Hosted LLM',
    author: 'Vercel',
    source: 'vercel.com',
    category: 'IA',
    description:
      'Hostear tu propio LLM rara vez gana en costo frente a la inferencia gestionada de modelos open-weight. Las cuatro condiciones que justifican tener tus propias GPUs.',
    url: 'https://vercel.com/i/self-hosted-llm',
    avatar: 'https://github.com/vercel.png?size=128',
    date: '2026-08-30',
    language: 'en',
  },
  {
    id: '42',
    title: '7 Best AI Gateways in 2026, Compared',
    author: 'Vercel',
    source: 'vercel.com',
    category: 'IA',
    description:
      'Comparación de Vercel AI Gateway, OpenRouter, Portkey, LiteLLM, Cloudflare, Kong y Helicone en failover, modelo de despliegue, latencia y precios.',
    url: 'https://vercel.com/i/best-ai-gateways',
    avatar: 'https://github.com/vercel.png?size=128',
    date: '2026-07-27',
    language: 'en',
  },
  {
    id: '43',
    title: 'What Is an AI Gateway?',
    author: 'Vercel',
    source: 'vercel.com',
    category: 'IA',
    description:
      'Un AI gateway es la capa de control entre tu aplicación y los proveedores de LLMs. Cómo funcionan el ruteo, el failover y el seguimiento de costos, y cuándo necesitás uno.',
    url: 'https://vercel.com/i/what-is-an-ai-gateway',
    avatar: 'https://github.com/vercel.png?size=128',
    date: '2026-07-24',
    language: 'en',
  },
  {
    id: '44',
    title: 'How to Build Production-Ready AI Agents',
    author: 'Vercel',
    source: 'vercel.com',
    category: 'IA',
    description:
      'Un framework práctico para definir el alcance, las herramientas y los guardrails de un agente de IA antes de que reciba tráfico real en producción.',
    url: 'https://vercel.com/i/how-to-build-production-ready-ai-agents',
    avatar: 'https://github.com/vercel.png?size=128',
    date: '2026-08-03',
    language: 'en',
  },
  {
    id: '45',
    title: 'AI Agent Evaluation Frameworks for Production',
    author: 'Vercel',
    source: 'vercel.com',
    category: 'IA',
    description:
      'Cómo evaluar agentes de IA en producción con chequeos ordenados, métricas binarias, evaluación de trazas y gates en CI para detectar fallas antes de deployar.',
    url: 'https://vercel.com/i/ai-agent-evaluation-frameworks-production',
    avatar: 'https://github.com/vercel.png?size=128',
    date: '2026-07-30',
    language: 'en',
  },
  {
    id: '46',
    title: 'Multimodal AI Explained: What Developers Need to Know',
    author: 'Vercel',
    source: 'vercel.com',
    category: 'IA',
    description:
      'Qué es la IA multimodal para un desarrollador web: cómo manejar texto, imágenes, audio y documentos con el AI SDK, patrones que funcionan en Next.js y por qué el costo ya no es una barrera.',
    url: 'https://vercel.com/i/multimodal-ai',
    avatar: 'https://github.com/vercel.png?size=128',
    date: '2026-07-23',
    language: 'en',
  },
  {
    id: '47',
    title: 'Fine-tuning vs RAG: When to Use Each',
    author: 'Anshuman Bhardwaj',
    source: 'vercel.com',
    category: 'IA',
    description:
      'El fine-tuning cambia el comportamiento del modelo, RAG le agrega conocimiento. Una guía para diagnosticar cuál necesitás, cuándo no usar ninguno y cómo construir ambos.',
    url: 'https://vercel.com/i/fine-tuning-vs-rag',
    avatar: '/lectura/anshuman-bhardwaj.webp',
    date: '2026-07-09',
    language: 'en',
  },
  {
    id: '48',
    title: 'Building Agentic AI Apps: A Problem-First Guide',
    author: 'Anshuman Bhardwaj',
    source: 'vercel.com',
    category: 'IA',
    description:
      'La mayoría de los proyectos de agentes arrancan por la tecnología. Un flujo paso a paso que empieza por el problema para definir, construir y llevar agentes de IA a producción.',
    url: 'https://vercel.com/i/building-agentic-ai-applications-with-a-problem-first-approach',
    avatar: '/lectura/anshuman-bhardwaj.webp',
    date: '2026-06-17',
    language: 'en',
  },
  {
    id: '49',
    title: 'Hexagonal Architecture',
    author: 'Alistair Cockburn',
    source: 'alistair.cockburn.us',
    category: 'Arquitectura',
    description:
      'El artículo original de Ports & Adapters: aislar la lógica de la aplicación detrás de puertos para que la UI, los tests, las bases de datos y otros sistemas se conecten mediante adaptadores intercambiables, sin que el núcleo dependa de ellos.',
    url: 'https://alistair.cockburn.us/hexagonal-architecture',
    avatar: '/lectura/alistair-cockburn.jpg',
    date: '2005-01-04',
    language: 'en',
  },
  {
    id: '50',
    title: 'What Is An LLM?',
    author: 'Matt Pocock',
    source: 'aihero.dev',
    category: 'IA',
    description:
      'Una introducción a los modelos de lenguaje grandes: qué son, cómo se ejecutan, qué son los tokens de entrada y las estrategias de muestreo, y cómo se crean e inspeccionan.',
    url: 'https://www.aihero.dev/what-is-an-llm',
    avatar: 'https://github.com/mattpocock.png?size=128',
    date: '2025-03-17',
    language: 'en',
  },
  {
    id: '51',
    title: 'What Is An AI Engineer?',
    author: 'Matt Pocock',
    source: 'aihero.dev',
    category: 'IA',
    description:
      'Define el rol del AI Engineer, lo diferencia del ML Engineering, del prompt engineering y del desarrollo asistido por IA, y explica cómo un dev web puede dar el salto.',
    url: 'https://www.aihero.dev/what-is-an-ai-engineer',
    avatar: 'https://github.com/mattpocock.png?size=128',
    date: '2025-03-26',
    language: 'en',
  },
  {
    id: '52',
    title: "What Can You Use LLM's For?",
    author: 'Matt Pocock',
    source: 'aihero.dev',
    category: 'IA',
    description:
      'Repasa para qué sirven los LLMs (estructurar datos, clasificar, responder preguntas, agentes) y cuándo te conviene usar un sistema determinístico en lugar de uno.',
    url: 'https://www.aihero.dev/what-are-llms-used-for',
    avatar: 'https://github.com/mattpocock.png?size=128',
    date: '2025-03-18',
    language: 'en',
  },
  {
    id: '53',
    title: '5 Questions To Ask Before Choosing An LLM',
    author: 'Matt Pocock',
    source: 'aihero.dev',
    category: 'IA',
    description:
      'Cinco preguntas para elegir el modelo adecuado para tu app: modelos abiertos o cerrados, costo por token, latencia, cómo medir el rendimiento y cuánto contexto necesitás.',
    url: 'https://www.aihero.dev/how-to-choose-an-llm',
    avatar: 'https://github.com/mattpocock.png?size=128',
    date: '2025-03-17',
    language: 'en',
  },
  {
    id: '54',
    title: 'The AI Engineer Mindset',
    author: 'Matt Pocock',
    source: 'aihero.dev',
    category: 'IA',
    description:
      'Explica por qué construir con LLMs exige pensar en sistemas probabilísticos, definir criterios de éxito claros y usar los datos reales de usuarios para mejorar continuamente tu aplicación.',
    url: 'https://www.aihero.dev/the-ai-engineer-mindset',
    avatar: 'https://github.com/mattpocock.png?size=128',
    date: '2025-03-24',
    language: 'en',
  },
  {
    id: '55',
    title: 'Your App Is Only As Good As Its Evals',
    author: 'Matt Pocock',
    source: 'aihero.dev',
    category: 'IA',
    description:
      'Presenta los evals como la herramienta clave para medir apps con LLMs: por qué el testing tradicional no alcanza, los tres tipos de evals y cómo armar un ciclo de mejora con datos.',
    url: 'https://www.aihero.dev/what-are-evals',
    avatar: 'https://github.com/mattpocock.png?size=128',
    date: '2024-11-18',
    language: 'en',
  },
  {
    id: '56',
    title: '17 Techniques For Improving Your LLM-Powered App',
    author: 'Matt Pocock',
    source: 'aihero.dev',
    category: 'IA',
    description:
      'Un catálogo de técnicas para mejorar tu app con LLMs, desde prompts con roles, XML y few-shot hasta salidas estructuradas, tool calling, RAG y loops agénticos, empezando siempre por lo más simple.',
    url: 'https://www.aihero.dev/how-to-improve-your-llm-powered-app',
    avatar: 'https://github.com/mattpocock.png?size=128',
    date: '2025-03-24',
    language: 'en',
  },
  {
    id: '57',
    title: 'The /grill-me Skill',
    author: 'Matt Pocock',
    source: 'aihero.dev',
    category: 'Programación',
    description:
      'Presenta el skill /grill-me, que te entrevista en rondas de preguntas sobre una idea todavía suelta hasta que puedas comprometerte con ella antes de ponerte a construir con tu agente.',
    url: 'https://www.aihero.dev/skills-grill-me',
    avatar: 'https://github.com/mattpocock.png?size=128',
    date: '2026-04-27',
    language: 'en',
  },
  {
    id: '58',
    title: 'grill-with-docs: Align Before You Build',
    author: 'Matt Pocock',
    source: 'aihero.dev',
    category: 'Programación',
    description:
      'Explica el skill /grill-with-docs, que combina la entrevista de grill-me con domain-driven design para que vos y el agente compartan un vocabulario y dejen las decisiones documentadas en el repo.',
    url: 'https://www.aihero.dev/grill-with-docs',
    avatar: 'https://github.com/mattpocock.png?size=128',
    date: '2026-05-05',
    language: 'en',
  },
  {
    id: '59',
    title: 'Essential AI Coding Feedback Loops For TypeScript Projects',
    author: 'Matt Pocock',
    source: 'aihero.dev',
    category: 'Programación',
    description:
      'Guía práctica para darle a tu agente de código feedback loops en proyectos TypeScript (type checking, tests, pre-commit hooks con Husky y formateo automático) para que verifique su propio trabajo.',
    url: 'https://www.aihero.dev/essential-ai-coding-feedback-loops-for-type-script-projects',
    avatar: 'https://github.com/mattpocock.png?size=128',
    date: '2026-01-16',
    language: 'en',
  },
  {
    id: '60',
    title: 'A Complete Guide To AGENTS.md',
    author: 'Matt Pocock',
    source: 'aihero.dev',
    category: 'Programación',
    description:
      'Cómo escribir un buen AGENTS.md: por qué los archivos enormes confunden al agente y gastan tokens, cómo recortarlos con progressive disclosure y cómo organizarlos en monorepos.',
    url: 'https://www.aihero.dev/a-complete-guide-to-agents-md',
    avatar: 'https://github.com/mattpocock.png?size=128',
    date: '2026-01-18',
    language: 'en',
  },
  {
    id: '61',
    title: 'An Introduction To Plan Mode',
    author: 'Matt Pocock',
    source: 'aihero.dev',
    category: 'Programación',
    description:
      'Cómo usar el plan mode de agentes como Claude Code para iterar sobre los requisitos antes de escribir código. Ojo: el autor lo actualizó y hoy recomienda /grill-with-docs en su lugar.',
    url: 'https://www.aihero.dev/plan-mode-introduction',
    avatar: 'https://github.com/mattpocock.png?size=128',
    date: '2026-01-09',
    language: 'en',
  },
  {
    id: '62',
    title: 'What Are Tokens?',
    author: 'Matt Pocock',
    source: 'aihero.dev',
    category: 'IA',
    description:
      'Explica qué son los tokens con los que trabajan los LLMs, cómo se codifican y decodifican, por qué importa el tamaño del vocabulario y cómo impactan en lo que pagás.',
    url: 'https://www.aihero.dev/what-are-tokens',
    avatar: 'https://github.com/mattpocock.png?size=128',
    date: '2025-09-30',
    language: 'en',
  },
  {
    id: '63',
    title: 'What Is The Context Window?',
    author: 'Matt Pocock',
    source: 'aihero.dev',
    category: 'IA',
    description:
      'Explica qué es la ventana de contexto de un modelo (tokens de entrada y salida), qué pasa cuando llegás a su límite y el problema de "lost in the middle".',
    url: 'https://www.aihero.dev/what-is-the-context-window',
    avatar: 'https://github.com/mattpocock.png?size=128',
    date: '2025-09-30',
    language: 'en',
  },
  {
    id: '64',
    title: 'What Are Tools?',
    author: 'Matt Pocock',
    source: 'aihero.dev',
    category: 'IA',
    description:
      'Explica cómo se le dan herramientas a un LLM desde el system prompt, la diferencia entre la llamada a una herramienta y su ejecución, y cómo manejar errores en el flujo completo.',
    url: 'https://www.aihero.dev/what-are-tools',
    avatar: 'https://github.com/mattpocock.png?size=128',
    date: '2025-09-30',
    language: 'en',
  },
  {
    id: '65',
    title: 'What Is An Agent?',
    author: 'Matt Pocock',
    source: 'aihero.dev',
    category: 'IA',
    description:
      'Compara agentes y workflows en sistemas con LLMs: los workflows siguen pasos predefinidos en código y los agentes improvisan, y explica cuándo te conviene cada uno.',
    url: 'https://www.aihero.dev/what-is-an-agent',
    avatar: 'https://github.com/mattpocock.png?size=128',
    date: '2025-09-30',
    language: 'en',
  },
  {
    id: '66',
    title: 'Product Engineers',
    author: 'Lee Robinson',
    source: 'leerob.com',
    category: 'Producto',
    description:
      'La división entre frontend y backend sirve cada vez menos. Qué es un product engineer, en qué se diferencia de un platform engineer y cómo encontrar ese perfil al contratar.',
    url: 'https://leerob.com/product-engineers',
    avatar: 'https://github.com/leerob.png?size=128',
    date: '2023-08-01',
    language: 'en',
  },
  {
    id: '67',
    title: 'Developer Experience AI: Designing DX for Agents and Humans',
    author: 'Felipe Barreiros',
    source: 'product.engineer',
    category: 'IA',
    description:
      'Si los agentes ya escriben buena parte del código, la experiencia de desarrollo no puede pensarse para un solo humano frente al editor. Cómo rediseñar IDE, testing, feedback loops y contexto para agentes y personas.',
    url: 'https://www.product.engineer/blog/developer-experience-ai-agents',
    avatar: 'https://github.com/felipebarreiros.png?size=128',
    date: '2026-08-22',
    language: 'en',
  },
  {
    id: '68',
    title: 'Product Engineer vs Designer: Where Ownership Overlaps',
    author: 'Felipe Barreiros',
    source: 'product.engineer',
    category: 'Producto',
    description:
      'Cuando los product engineers toman decisiones de UX, el choque con diseño es casi inevitable. Un modelo de ownership compartido para colaborar, evitar errores típicos y saber cuándo hace falta un diseñador.',
    url: 'https://www.product.engineer/blog/product-engineer-vs-designer',
    avatar: 'https://github.com/felipebarreiros.png?size=128',
    date: '2026-08-19',
    language: 'en',
  },
  {
    id: '69',
    title: 'Product Engineer vs Project Manager: Not Even Close',
    author: 'Felipe Barreiros',
    source: 'product.engineer',
    category: 'Producto',
    description:
      'Comparten una palabra y nada más: uno construye y se hace cargo del resultado, el otro coordina plazos y dependencias. Por qué confundir ambos roles es peligroso y si se puede pasar de uno al otro.',
    url: 'https://www.product.engineer/blog/product-engineer-vs-project-manager',
    avatar: 'https://github.com/felipebarreiros.png?size=128',
    date: '2026-08-11',
    language: 'en',
  },
  {
    id: '70',
    title: 'The Future of CI/CD Is Not a Pipeline',
    author: 'Felipe Barreiros',
    source: 'product.engineer',
    category: 'Programación',
    description:
      'Los pipelines de CI/CD acumulan pasos frágiles y reglas que nadie recuerda. La propuesta: reemplazarlos por agentes que deciden cómo testear, deployar según el estado de producción y monitorear con contexto.',
    url: 'https://www.product.engineer/blog/cicd-is-dead',
    avatar: 'https://github.com/felipebarreiros.png?size=128',
    date: '2026-08-07',
    language: 'en',
  },
  {
    id: '71',
    title: 'Associate Product Engineer: Entry-Level Path to Ownership',
    author: 'Felipe Barreiros',
    source: 'product.engineer',
    category: 'Carrera',
    description:
      'No hace falta esperar un ascenso para hacerte cargo de resultados. Cómo pensar como product engineer desde tu primer trabajo, qué buscan los hiring managers y un plan concreto para tus primeros 90 días.',
    url: 'https://www.product.engineer/blog/associate-product-engineer',
    avatar: 'https://github.com/felipebarreiros.png?size=128',
    date: '2026-08-06',
    language: 'en',
  },
  {
    id: '72',
    title: 'How to Build an Agent-Ready Codebase',
    author: 'Felipe Barreiros',
    source: 'product.engineer',
    category: 'IA',
    description:
      'Darle a un agente acceso a todo el repo no alcanza si el código no le explica cómo se conectan las piezas. Los cuatro pilares de un codebase listo para agentes, cómo auditarlo y un plan semana a semana.',
    url: 'https://www.product.engineer/blog/making-codebase-agent-ready',
    avatar: 'https://github.com/felipebarreiros.png?size=128',
    date: '2026-07-30',
    language: 'en',
  },
  {
    id: '73',
    title: 'User Research for Engineers: Ship Better Products Without a Research Team',
    author: 'Felipe Barreiros',
    source: 'product.engineer',
    category: 'Producto',
    description:
      'Tus usuarios te están diciendo todo, el tema es escucharlos. Cinco métodos de user research que entran en el flujo de trabajo de un dev, cómo armar el hábito semanal y convertir señales en cambios.',
    url: 'https://www.product.engineer/blog/product-engineer-user-research',
    avatar: 'https://github.com/felipebarreiros.png?size=128',
    date: '2026-07-28',
    language: 'en',
  },
  {
    id: '74',
    title: 'Product Engineering Manager: What the Role Looks Like',
    author: 'Felipe Barreiros',
    source: 'product.engineer',
    category: 'Producto',
    description:
      'Liderar product engineers con el manual de un engineering manager tradicional no funciona. Un marco de coaching, career ladder, ritmo semanal y errores comunes para gestionar equipos orientados a resultados.',
    url: 'https://www.product.engineer/blog/product-engineering-manager',
    avatar: 'https://github.com/felipebarreiros.png?size=128',
    date: '2026-07-23',
    language: 'en',
  },
  {
    id: '75',
    title: 'Harness Engineering: When Humans Steer and Agents Execute',
    author: 'Felipe Barreiros',
    source: 'product.engineer',
    category: 'IA',
    description:
      'Un agente que sigue instrucciones al pie de la letra también puede borrarte la base de datos. Qué es harness engineering y cómo diseñar límites, checkpoints y controles para que los agentes operen seguros en producción.',
    url: 'https://www.product.engineer/blog/harness-engineering',
    avatar: 'https://github.com/felipebarreiros.png?size=128',
    date: '2026-07-22',
    language: 'en',
  },
  {
    id: '76',
    title: 'Product Engineer Skills: The Complete Competency Map',
    author: 'Felipe Barreiros',
    source: 'product.engineer',
    category: 'Producto',
    description:
      'Basta de listas de buzzwords. Un mapa de competencias de product engineer organizado en Define, Build y Ship, con una rúbrica para autoevaluarte y qué practicar según la etapa de la empresa.',
    url: 'https://www.product.engineer/blog/product-engineer-skills',
    avatar: 'https://github.com/felipebarreiros.png?size=128',
    date: '2026-07-21',
    language: 'en',
  },
  {
    id: '77',
    title: 'Spec-Driven Development: Writing Specs, Not Code',
    author: 'Felipe Barreiros',
    source: 'product.engineer',
    category: 'Programación',
    description:
      'El código se escribe solo, la spec no. Qué es spec-driven development, cómo es una especificación ejecutable que un agente convierte en software y cómo lo aplicó Amazon con Kiro.',
    url: 'https://www.product.engineer/blog/spec-driven-development',
    avatar: 'https://github.com/felipebarreiros.png?size=128',
    date: '2026-07-17',
    language: 'en',
  },
  {
    id: '78',
    title: 'Post-Agile Software Development: Moving Away from Agile',
    author: 'Felipe Barreiros',
    source: 'product.engineer',
    category: 'Programación',
    description:
      'Un fix de cuatro horas que espera once días por el sprint puede costar miles de usuarios. Por qué los equipos de product engineers están dejando Agile y cómo es la transición a un modelo post-agile.',
    url: 'https://www.product.engineer/blog/moving-away-from-agile',
    avatar: 'https://github.com/felipebarreiros.png?size=128',
    date: '2026-07-14',
    language: 'en',
  },
  {
    id: '79',
    title: "The Product Engineer's Guide to Metrics and Measurement",
    author: 'Felipe Barreiros',
    source: 'product.engineer',
    category: 'Producto',
    description:
      'Lo shippeaste, ahora demostrá que importó. Qué métricas seguir en cada etapa, cómo instrumentar sin frenar al equipo y cómo presentar resultados que impulsen decisiones y tu carrera.',
    url: 'https://www.product.engineer/blog/product-engineer-metrics',
    avatar: 'https://github.com/felipebarreiros.png?size=128',
    date: '2026-07-11',
    language: 'en',
  },
  {
    id: '80',
    title: 'Go-to-Market for Engineers',
    author: 'Felipe Barreiros',
    source: 'product.engineer',
    category: 'Producto',
    description:
      'Mergeaste, el CI está en verde y nadie usa la feature. Cómo un product engineer se hace cargo de la distribución, el onboarding y la activación para que lo que sale a producción llegue a sus usuarios.',
    url: 'https://www.product.engineer/blog/product-engineer-guide-go-to-market',
    avatar: 'https://github.com/felipebarreiros.png?size=128',
    date: '2026-07-10',
    language: 'en',
  },
  {
    id: '81',
    title: 'Fly Ahead of the Airplane: A Product Engineer Mindset',
    author: 'Felipe Barreiros',
    source: 'product.engineer',
    category: 'Carrera',
    description:
      'En aviación, volar detrás del avión mata. A partir de su experiencia como piloto, el autor propone anticiparte con tu código, tus herramientas y tu carrera para no quedar atrás en la era de la IA.',
    url: 'https://www.product.engineer/blog/fly-ahead-of-the-airplane',
    avatar: 'https://github.com/felipebarreiros.png?size=128',
    date: '2026-07-10',
    language: 'en',
  },
  {
    id: '82',
    title: 'The Multi-Agent Architecture That Actually Ships',
    author: 'Felipe Barreiros',
    source: 'product.engineer',
    category: 'Arquitectura',
    description:
      'La mayoría de los sistemas multiagente nunca pasan de la demo. Desarma la arquitectura que Factory AI usa en producción: cómo se coordinan los agentes, qué patrones podés copiar y en qué fallan.',
    url: 'https://www.product.engineer/blog/multi-agent-architecture-ships',
    avatar: 'https://github.com/felipebarreiros.png?size=128',
    date: '2026-07-09',
    language: 'en',
  },
  {
    id: '83',
    title: 'The Future of Software Engineering Is Plan and Review',
    author: 'Felipe Barreiros',
    source: 'product.engineer',
    category: 'Programación',
    description:
      'El trabajo pasó de escribir código a dirigir agentes que lo escriben. Qué significa hoy planificar con especificaciones precisas y revisar lo que generan, y qué habilidades necesitás para hacerlo bien.',
    url: 'https://www.product.engineer/blog/software-engineering-plan-and-review',
    avatar: 'https://github.com/felipebarreiros.png?size=128',
    date: '2026-07-08',
    language: 'en',
  },
  {
    id: '84',
    title: 'Vibe Coding vs Vibe Engineering: What Actually Changes',
    author: 'Felipe Barreiros',
    source: 'product.engineer',
    category: 'IA',
    description:
      'Un prototipo hecho con IA en cuatro horas puede caerse en producción en una semana. Un modelo de madurez para pasar del vibe coding al vibe engineering, con validaciones, controles y ciclos de feedback.',
    url: 'https://www.product.engineer/blog/vibe-coding-to-vibe-engineering',
    avatar: 'https://github.com/felipebarreiros.png?size=128',
    date: '2026-07-07',
    language: 'en',
  },
  {
    id: '85',
    title: 'From Product Manager to Product Engineer: Adding Technical Depth',
    author: 'Felipe Barreiros',
    source: 'product.engineer',
    category: 'Carrera',
    description:
      'Si sos PM ya sabés qué construir; te falta la otra mitad. Una hoja de ruta de seis meses para sumar base técnica, aprovechar tu ventaja de producto y saber cuándo estás listo para el cambio.',
    url: 'https://www.product.engineer/blog/product-manager-to-product-engineer',
    avatar: 'https://github.com/felipebarreiros.png?size=128',
    date: '2026-07-04',
    language: 'en',
  },
  {
    id: '86',
    title: 'Context Engineering: The Skill That Replaced Prompt Engineering',
    author: 'Felipe Barreiros',
    source: 'product.engineer',
    category: 'IA',
    description:
      'El prompt engineering tocó techo: lo que hace confiable a un agente es el contexto que recibe. Cómo armar un sistema de contexto, qué patrones se usan en producción y qué errores evitar.',
    url: 'https://www.product.engineer/blog/context-engineering',
    avatar: 'https://github.com/felipebarreiros.png?size=128',
    date: '2026-07-01',
    language: 'en',
  },
  {
    id: '87',
    title: "Product Engineer vs Full-Stack Developer: What's Different?",
    author: 'Felipe Barreiros',
    source: 'product.engineer',
    category: 'Producto',
    description:
      'Full-stack es saber construir en todas las capas técnicas; product engineer es hacerse cargo del resultado, del problema del usuario a la métrica de negocio. Qué comparten ambos roles, qué no y cuándo conviene cada uno.',
    url: 'https://www.product.engineer/blog/product-engineer-vs-full-stack',
    avatar: 'https://github.com/felipebarreiros.png?size=128',
    date: '2026-06-30',
    language: 'en',
  },
  {
    id: '88',
    title: 'How to Build a Product Engineer Portfolio That Proves Impact',
    author: 'Felipe Barreiros',
    source: 'product.engineer',
    category: 'Carrera',
    description:
      'Tu CV dice qué hiciste; tu portfolio tiene que mostrar qué cambió. Un marco de casos de estudio con métricas de antes y después, plantillas y formas de presentar trabajo que no fue enteramente tuyo.',
    url: 'https://www.product.engineer/blog/product-engineer-impact-portfolio',
    avatar: 'https://github.com/felipebarreiros.png?size=128',
    date: '2026-06-24',
    language: 'en',
  },
  {
    id: '89',
    title: 'From Software Engineer to Product Engineer: The Complete Transition Guide',
    author: 'Felipe Barreiros',
    source: 'product.engineer',
    category: 'Carrera',
    description:
      'Si hace años que escribís buen código pero construís cosas que nadie usa, esta guía es para vos. Un plan de 12 semanas para pasar de implementar a hacerte cargo del resultado, armar tu portfolio y conseguir el rol.',
    url: 'https://www.product.engineer/blog/software-engineer-to-product-engineer',
    avatar: 'https://github.com/felipebarreiros.png?size=128',
    date: '2026-06-13',
    language: 'en',
  },
  {
    id: '90',
    title: 'How to Become a Product Engineer (Without Starting Over)',
    author: 'Felipe Barreiros',
    source: 'product.engineer',
    category: 'Carrera',
    description:
      'No hace falta renunciar ni hacer un bootcamp: si ya programás, estás más cerca de lo que creés. Una transición en cuatro fases, las habilidades a priorizar y los cambios de mentalidad que más pesan.',
    url: 'https://www.product.engineer/blog/how-to-become-a-product-engineer',
    avatar: 'https://github.com/felipebarreiros.png?size=128',
    date: '2026-05-28',
    language: 'en',
  },
  {
    id: '91',
    title: 'The Product Engineer Interview: 30+ Questions That Actually Get Asked',
    author: 'Felipe Barreiros',
    source: 'product.engineer',
    category: 'Carrera',
    description:
      'Las entrevistas de product engineer evalúan si sabés decidir qué construir, no solo cómo. Treinta y tres preguntas reales de producto, técnicas y de impacto, con marcos para responder y un plan de preparación de dos semanas.',
    url: 'https://www.product.engineer/blog/product-engineer-interview',
    avatar: 'https://github.com/felipebarreiros.png?size=128',
    date: '2026-05-29',
    language: 'en',
  },
  {
    id: '92',
    title: 'Product Engineer vs Software Engineer: What Actually Changes',
    author: 'Felipe Barreiros',
    source: 'product.engineer',
    category: 'Producto',
    description:
      'No es un cambio de nombre para el mismo trabajo. Una comparación lado a lado de responsabilidades, habilidades, sueldos y caminos de carrera, con las cinco cosas que cambian de verdad y las que se mantienen.',
    url: 'https://www.product.engineer/blog/product-engineer-vs-software-engineer',
    avatar: 'https://github.com/felipebarreiros.png?size=128',
    date: '2026-05-26',
    language: 'en',
  },
  {
    id: '93',
    title: 'Agentic Coding: Best Practices for Building Software with AI Agents',
    author: 'Agustín Sánchez',
    source: 'eagerworks.com',
    category: 'IA',
    description:
      'Buenas prácticas para construir software con agentes de IA sin perder calidad: cómo darles contexto, revisar lo que producen y evitar que la velocidad se convierta en deuda técnica.',
    url: 'https://eagerworks.com/blog/agentic-coding-best-practices',
    avatar: '/lectura/agustin-sanchez.webp',
    date: '2026-07-23',
    language: 'en',
  },
  {
    id: '94',
    title: 'AI and Engineering Process: Why Fundamentals Matter More Than Ever',
    author: 'Santiago Bertinat',
    source: 'eagerworks.com',
    category: 'Programación',
    description:
      'La IA no arregla sistemas rotos: el proceso de ingeniería, la arquitectura y las decisiones de equipo siguen definiendo si un desarrollo asistido por IA sale bien o no.',
    url: 'https://eagerworks.com/blog/ai-engineering-process',
    avatar: '/lectura/santiago-bertinat.webp',
    date: '2026-04-28',
    language: 'en',
  },
  {
    id: '95',
    title: 'Vibe Coding: How LLMs are reshaping the way we build software',
    author: 'Juan Pablo Balarini',
    source: 'eagerworks.com',
    category: 'IA',
    description:
      'Qué es el vibe coding, guiar a un modelo con la intención en vez de escribir cada línea, y cómo lo usan en el día a día con herramientas como Cursor para pasar de idea a software funcionando.',
    url: 'https://eagerworks.com/blog/vibe-coding',
    avatar: '/lectura/juan-pablo-balarini.webp',
    date: '2025-07-03',
    language: 'en',
  },
  {
    id: '96',
    title: 'Introduction to the Software Testing Life Cycle (STLC)',
    author: 'eagerworks',
    source: 'eagerworks.com',
    category: 'Programación',
    description:
      'El testing no es la última fase antes de salir: es un proceso que atraviesa todo el desarrollo. Una introducción clara a las etapas del STLC, pensada también para quien no es de QA.',
    url: 'https://eagerworks.com/blog/software-testing-life-cycle',
    avatar: 'https://github.com/eagerworks.png?size=128',
    date: '2025-05-07',
    language: 'en',
  },
  {
    id: '97',
    title: 'From Design to Developing: essential tips for effective teamwork',
    author: 'Agustina Rañales',
    source: 'eagerworks.com',
    category: 'Diseño',
    description:
      'Estrategias y herramientas para que diseño y desarrollo trabajen como un solo equipo, incluso entre continentes: handoffs, comunicación y cómo construir productos desde cero sin fricción.',
    url: 'https://eagerworks.com/blog/design-development-teamwork',
    avatar: '/lectura/agustina-ranales.webp',
    date: '2025-06-12',
    language: 'en',
  },
  {
    id: '98',
    title: 'How to augment your RAG architecture with Knowledge Graphs',
    author: 'Juan Pablo Balarini',
    source: 'eagerworks.com',
    category: 'IA',
    description:
      'Cómo funcionan los grafos de conocimiento y RAG, por qué se complementan y cómo combinarlos hoy en tus proyectos usando GraphRAG.',
    url: 'https://eagerworks.com/blog/rag-and-knowledge-graphs',
    avatar: '/lectura/juan-pablo-balarini.webp',
    date: '2024-09-13',
    language: 'en',
  },
  {
    id: '99',
    title: 'Navigating cross-cultural design: key considerations for global success',
    author: 'Agustina Rañales',
    source: 'eagerworks.com',
    category: 'Diseño',
    description:
      'Los productos ya no tienen fronteras: qué tener en cuenta al diseñar para usuarios de otras culturas, desde el idioma y los colores hasta las convenciones de uso.',
    url: 'https://eagerworks.com/blog/cross-cultural-design',
    avatar: '/lectura/agustina-ranales.webp',
    date: '2024-11-28',
    language: 'en',
  },
  {
    id: '100',
    title: 'An introduction to RAG: Retrieval Augmented Generation explained',
    author: 'Juan Pablo Balarini',
    source: 'eagerworks.com',
    category: 'IA',
    description:
      'Una introducción a RAG: cómo darle a un LLM el contexto relevante en el momento de responder para que deje de inventar y conteste algo útil.',
    url: 'https://eagerworks.com/blog/retrieval-augmented-generation',
    avatar: '/lectura/juan-pablo-balarini.webp',
    date: '2024-02-27',
    language: 'en',
  },
  {
    id: '101',
    title: 'Text summarization through AI: the power of clustering',
    author: 'Juan Pablo Balarini',
    source: 'eagerworks.com',
    category: 'IA',
    description:
      'Resumir grandes volúmenes de documentación con GPT sale caro porque se paga por token. El clustering permite agrupar y categorizar el texto antes, para resumir de forma más eficiente.',
    url: 'https://eagerworks.com/blog/clustering-ai',
    avatar: '/lectura/juan-pablo-balarini.webp',
    date: '2024-06-04',
    language: 'en',
  },
  {
    id: '102',
    title: 'RAG integration: empowering document management with DocsHunter',
    author: 'Juan Pablo Balarini',
    source: 'eagerworks.com',
    category: 'IA',
    description:
      'Un caso real de RAG en producción: cómo integraron la técnica en Docs Hunter para resumir documentos, responder preguntas sobre ellos y armar chatbots para empresas.',
    url: 'https://eagerworks.com/blog/docs-hunter-rag',
    avatar: '/lectura/juan-pablo-balarini.webp',
    date: '2024-03-28',
    language: 'en',
  },
  {
    id: '103',
    title: 'Beyond words: the AI approach to text generation',
    author: 'Juan Pablo Balarini',
    source: 'eagerworks.com',
    category: 'IA',
    description:
      'Cómo usar IA para generar documentos de forma rápida y precisa en organizaciones grandes, ahorrando tiempo sin descuidar la exactitud ni el cumplimiento normativo.',
    url: 'https://eagerworks.com/blog/ai-for-text-generation',
    avatar: '/lectura/juan-pablo-balarini.webp',
    date: '2024-07-25',
    language: 'en',
  },
  {
    id: '104',
    title: 'Exploring the potential of Progressive Web Applications',
    author: 'eagerworks',
    source: 'eagerworks.com',
    category: 'Programación',
    description:
      'Las PWAs combinan lo mejor de la web y de las apps nativas: qué son, qué ventajas tienen para usuarios y equipos, y cuándo conviene elegirlas en lugar de una app tradicional.',
    url: 'https://eagerworks.com/blog/progressive-web-applications',
    avatar: 'https://github.com/eagerworks.png?size=128',
    date: '2024-07-04',
    language: 'en',
  },
  {
    id: '105',
    title: 'Singletons y carreras de datos',
    author: 'Mauricio Sánchez',
    source: 'medium.com',
    category: 'Programación',
    description:
      'Por qué un Singleton mal sincronizado expone tu app a carreras de datos y crashes como EXC_BAD_ACCESS, y cómo hacerlo thread-safe en iOS con conceptos que aplican a cualquier tecnología.',
    url: 'https://medium.com/@mauriciosnchz/singletons-y-carreras-de-datos-38d3963d7fbc',
    avatar: '/lectura/mauricio-sanchez.webp',
    date: '2026-06-17',
    language: 'es',
  },
  {
    id: '106',
    title: 'Buscando el diseño perfecto',
    author: 'Mauricio Sánchez',
    source: 'medium.com',
    category: 'Arquitectura',
    description:
      '¿Existe un diseño capaz de resolver todos los casos a medida que un sistema evoluciona? Eficacia, eficiencia, flexibilidad y fiabilidad a través de la evolución de la plataforma de PedidosYa.',
    url: 'https://medium.com/peya-tech/buscando-el-dise%C3%B1o-perfecto-0651723fb26b',
    avatar: '/lectura/mauricio-sanchez.webp',
    date: '2025-07-04',
    language: 'es',
  },
  {
    id: '107',
    title: 'Growing Pains: Mejorando la performance de componentes iOS',
    author: 'Mauricio Sánchez',
    source: 'medium.com',
    category: 'Programación',
    description:
      'Al migrar un flujo de PedidosYa de web a nativo con Server Driven UI, la carga mejoró pero aparecieron app hangs: los enfoques que probaron para resolverlos y qué resultados dio cada uno.',
    url: 'https://medium.com/peya-tech/growing-pains-mejorando-la-performance-de-componentes-ios-ef80db706f81',
    avatar: '/lectura/mauricio-sanchez.webp',
    date: '2024-10-16',
    language: 'es',
  },
  {
    id: '108',
    title: 'Loop Engineering: From Backlog Issue to Shipped Code',
    author: 'Agustín Sánchez',
    source: 'dizenz.com',
    category: 'IA',
    description:
      'Cómo cerraron el ciclo del agentic coding en DIZENZ: de un issue crudo del backlog a código desplegado en un entorno de prueba, con dos agentes de Claude Code, una revisión en dos pasadas y un quality gate que corre en la laptop en vez de en GitHub Actions.',
    url: 'https://www.dizenz.com/blog/loop-engineering',
    avatar: '/lectura/agustin-sanchez.webp',
    date: '2026-08-17',
    language: 'en',
  },
  {
    id: '109',
    title: 'Crashout: A Multiplayer Racing Game Built for Live Events',
    author: 'Agustín Sánchez',
    coauthors: ['Santiago Villada'],
    source: 'dizenz.com',
    category: 'Arquitectura',
    description:
      'Cómo construyeron Crashout, un juego de carreras multijugador para eventos en vivo que se controla desde el celular: un servidor autoritativo en Go, tres pantallas sincronizadas y acceso por QR sin instalar ninguna app.',
    url: 'https://www.dizenz.com/blog/crashout',
    avatar: '/lectura/agustin-sanchez.webp',
    date: '2026-08-15',
    language: 'en',
  },
  {
    id: '110',
    title: 'Building an AI Agent With the Vercel AI SDK and eve',
    author: 'Agustín Sánchez',
    source: 'dizenz.com',
    category: 'IA',
    description:
      'Paso a paso con el agente real que arma quizzes en Qüizo: de una sola llamada a generateObject a un agente de eve con tools y aislado por tenant, salida estructurada con dos schemas y revisión humana antes de guardar.',
    url: 'https://www.dizenz.com/blog/ai-agents-with-eve',
    avatar: '/lectura/agustin-sanchez.webp',
    date: '2026-08-23',
    language: 'en',
  },
  {
    id: '111',
    title: 'Agent Skills: Teaching an AI Agent What Your Team Already Knows',
    author: 'Agustín Sánchez',
    source: 'dizenz.com',
    category: 'IA',
    description:
      'Qué son las Agent Skills, qué problema resuelven y cómo crear, publicar y actualizar una: desde un único SKILL.md hasta un plugin compartido con todo el equipo.',
    url: 'https://www.dizenz.com/blog/agent-skills',
    avatar: '/lectura/agustin-sanchez.webp',
    date: '2026-08-23',
    language: 'en',
  },
  {
    id: '112',
    title: 'MCP Servers: How AI Agents Connect to Real Tools and Data',
    author: 'Agustín Sánchez',
    source: 'dizenz.com',
    category: 'IA',
    description:
      'Qué es el Model Context Protocol, el problema de integración que resuelve y cómo construir, desplegar y conectar un servidor MCP a Claude.',
    url: 'https://www.dizenz.com/blog/mcp-servers',
    avatar: '/lectura/agustin-sanchez.webp',
    date: '2026-08-23',
    language: 'en',
  },
  {
    id: '113',
    title: 'Agent-Native Architectures: Designing Systems Agents Can Operate',
    author: 'Agustín Sánchez',
    source: 'dizenz.com',
    category: 'Arquitectura',
    description:
      'Por qué la próxima generación de software va a tratar a los agentes como operadores de primera clase: las cuatro propiedades que hacen a un sistema agent-native y por qué pensarlo así se vuelve una habilidad central de arquitectura.',
    url: 'https://www.dizenz.com/blog/agent-native-architectures',
    avatar: '/lectura/agustin-sanchez.webp',
    date: '2026-08-17',
    language: 'en',
  },
  {
    id: '114',
    title: 'Mingüini: Building an All-in-One Productivity Platform',
    author: 'Agustín Sánchez',
    coauthors: ['Victoria Grillo'],
    source: 'dizenz.com',
    category: 'Arquitectura',
    description:
      'Cómo hicieron de Mingüini una plataforma de productividad todo en uno: un solo modelo de datos, un solo límite de autenticación y trece módulos sobre Next.js 16, Server Actions y Prisma, en lugar de cinco apps separadas.',
    url: 'https://www.dizenz.com/blog/minguini',
    avatar: '/lectura/agustin-sanchez.webp',
    date: '2026-08-16',
    language: 'en',
  },
  {
    id: '115',
    title: 'Qüizo: A Multiplayer Quiz Game Built for Live Events',
    author: 'Agustín Sánchez',
    source: 'dizenz.com',
    category: 'Arquitectura',
    description:
      'Cómo construyeron Qüizo, una plataforma de quizzes multijugador para eventos en vivo: un servidor que es dueño del reloj, una capa de SSE que aguanta el wifi del lugar y pruebas de carga para saber cuánta gente entra de verdad en una sala.',
    url: 'https://www.dizenz.com/blog/quizo',
    avatar: '/lectura/agustin-sanchez.webp',
    date: '2026-08-16',
    language: 'en',
  },
  {
    id: '116',
    title: 'programaConNosotros: Building the Platform for a Community We Co-Founded',
    author: 'Agustín Sánchez',
    source: 'dizenz.com',
    category: 'Producto',
    description:
      'Cómo programaConNosotros pasó de ser un grupo de WhatsApp a una plataforma social open source: Next.js 16, Server Actions, Prisma y una base de contribuidores que crece junto con la comunidad.',
    url: 'https://www.dizenz.com/blog/pcn',
    avatar: '/lectura/agustin-sanchez.webp',
    date: '2026-08-15',
    language: 'en',
  },
  {
    id: '117',
    title: 'Agentic Coding: The Multiplier for Engineering Efficiency',
    author: 'Agustín Sánchez',
    source: 'dizenz.com',
    category: 'IA',
    description:
      'Cómo el agentic coding cambia el desarrollo de software en DIZENZ: cómo usan Claude Code, cómo eligen el modelo para cada tarea y qué buenas prácticas siguen al programar con IA.',
    url: 'https://www.dizenz.com/blog/agentic-coding',
    avatar: '/lectura/agustin-sanchez.webp',
    date: '2026-02-15',
    language: 'en',
  },
];

export const articles = [...allArticles].sort((a, b) => b.date.localeCompare(a.date));

/** Everyone who signed an article: its author first, then any coauthors. */
export const articleAuthors = (article: Article) => [article.author, ...(article.coauthors ?? [])];
