export type Talk = {
  name: string;
  speakerName: string;
  portrait?: string;
  date: Date;
  youtubeUrl?: string;
  location?: string;
  slides?: string[];
};

export const talks: Talk[] = [
  {
    name: 'Arquitectura de software: frontend, backend, bases de datos y más',
    speakerName: 'Agustín Sánchez',
    portrait: '/lightning-talks/arquitectura-software.jpeg',
    date: new Date('2023-05-06'),
    location: 'UTN (Tucumán, Argentina)',
  },
  {
    name: 'Arquitectura modular en aplicaciones móviles',
    speakerName: 'Mauricio Sánchez',
    portrait: '/lightning-talks/arquitectura-modular.jpeg',
    date: new Date('2023-05-06'),
    location: 'UTN (Tucumán, Argentina)',
  },
  {
    name: 'Depuración de código',
    speakerName: 'Tobías Paz Posse',
    portrait: '/lightning-talks/debugging.jpeg',
    date: new Date('2023-05-06'),
    location: 'UTN (Tucumán, Argentina)',
  },
  {
    name: 'Paradigmas de programación',
    speakerName: 'Marcelo Núñez',
    portrait: '/lightning-talks/paradigmas.jpeg',
    date: new Date('2023-05-06'),
    location: 'UTN (Tucumán, Argentina)',
  },
  {
    name: 'La Shell',
    speakerName: 'Marcelo Núnez',
    date: new Date('2023-09-16'),
    location: 'UTN (Tucumán, Argentina)',
    portrait: '/lightning-talks/la-shell.jpeg',
  },
  {
    name: 'Ingeniería en sistemas de información',
    speakerName: 'Marcelo Núnez',
    date: new Date('2023-09-16'),
    location: 'UTN (Tucumán, Argentina)',
    portrait: '/lightning-talks/ingenieria-en-sistemas.jpeg',
  },
  {
    name: 'Programación optimizada con ChatGPT',
    speakerName: 'Facundo Bazán',
    portrait: '/lightning-talks/chatgpt.jpeg',
    date: new Date('2023-05-06'),
    location: 'UTN (Tucumán, Argentina)',
  },
  {
    name: 'Java funcional: agilizando el procesamiento de datos',
    speakerName: 'Marcelo Núñez',
    portrait: '/lightning-talks/java-funcional.jpeg',
    date: new Date('2023-05-06'),
    location: 'UTN (Tucumán, Argentina)',
  },
  {
    name: 'Database indexing',
    speakerName: 'Josefina Japaze',
    portrait: '/lightning-talks/database-indexing.jpeg',
    date: new Date('2023-09-16'),
    location: 'UTN (Tucumán, Argentina)',
  },
  {
    name: 'Introducción al unit testing',
    speakerName: 'Tobías Paz Posse',
    portrait: '/lightning-talks/unit-testing.jpg',
    date: new Date('2023-09-16'),
    location: 'UTN (Tucumán, Argentina)',
  },
  {
    name: 'Domain-driven design, hexagonal architecture & vertical slicing',
    speakerName: 'Agustín Sánchez',
    portrait: '/lightning-talks/ddd-y-hexagonal-6.jpeg',
    date: new Date('2023-09-16'),
    location: 'UTN (Tucumán, Argentina)',
  },
  {
    name: 'Diseño perfecto',
    speakerName: 'Mauricio Sánchez',
    portrait: '/lightning-talks/diseno-perfecto.jpeg',
    date: new Date('2023-09-16'),
    location: 'UTN (Tucumán, Argentina)',
  },

  {
    name: 'Sitios para alojar repositorios de Git',
    speakerName: 'Camila Rodriguez',
    date: new Date('2021-10-09'),
    youtubeUrl: 'https://www.youtube.com/live/QMyCntZ5rIY?si=24Y1uD9PtsoDVqGo&t=934',
  },
  {
    name: 'Creación de repositorios en GitHub y conexión a repositorio local',
    speakerName: 'Marcelo Núñez',
    date: new Date('2021-10-09'),
    youtubeUrl: 'https://www.youtube.com/live/QMyCntZ5rIY?si=gd0ubcoGW1iQokM-&t=1281',
  },
  {
    name: 'Subida de cambios locales a repositorio de GitHub',
    speakerName: 'Lucas Pérez',
    date: new Date('2021-10-09'),
    youtubeUrl: 'https://www.youtube.com/live/QMyCntZ5rIY?si=_6U8-KJkfOUKs1_U&t=1921',
  },
  {
    name: 'Conflictos y soluciones trabajando en equipo usando Git y GitHub',
    speakerName: 'Mauricio Sánchez y Tobías Paz Posse',
    date: new Date('2021-10-09'),
    youtubeUrl: 'https://www.youtube.com/live/QMyCntZ5rIY?si=qkz-Sg3tmtuWuXnV&t=2631',
  },
  {
    name: 'Repaso de conceptos básicos de computación y desarrollo de software',
    speakerName: 'Lucas Perez',
    date: new Date('2021-06-26'),
    youtubeUrl: 'https://www.youtube.com/live/4yBLY947A0E?si=VyGzfqBG3HjG904J&t=742',
  },
  {
    name: '¿Qué es un sistema de control de versiones y cómo nos beneficia utilizarlo?',
    speakerName: 'Mauricio Sánchez',
    date: new Date('2021-06-26'),
    youtubeUrl: 'https://www.youtube.com/live/4yBLY947A0E?si=x4WrBIMy5C3R4CYQ&t=1629',
  },
  {
    name: 'Conceptos fundamentales de Git',
    speakerName: 'Marcelo Nuñez',
    date: new Date('2021-06-26'),
    youtubeUrl: 'https://www.youtube.com/live/4yBLY947A0E?si=WWX9mB65_rO6t2KK&t=1932',
  },
  {
    name: 'Instalación de Git en Windows y Linux',
    speakerName: 'Jeremías Moreno Ivanoff',
    date: new Date('2021-06-26'),
    youtubeUrl: 'https://www.youtube.com/live/4yBLY947A0E?si=Poyd76WCSBR9PdCE&t=2785',
  },
  {
    name: 'Workflow básico local con Git y C/C++',
    speakerName: 'Agustín Sánchez',
    date: new Date('2021-06-26'),
    youtubeUrl: 'https://www.youtube.com/live/4yBLY947A0E?si=D8qRBMKdjMchkYEQ&t=3633',
  },
  {
    name: 'Claves de la ingeniería en sistemas',
    speakerName: 'Agustín Sánchez',
    date: new Date('2021-04-24'),
    youtubeUrl: 'https://www.youtube.com/live/7F1m0PwHO38?si=V9T2ovOXMAx-ErB1&t=681',
  },
  {
    name: '¿Qué es un algoritmo?',
    speakerName: 'Mauricio Sánchez',
    date: new Date('2021-04-24'),
    youtubeUrl: 'https://www.youtube.com/live/7F1m0PwHO38?si=JFtHNSBVVcdH-30U&t=1591',
  },
  {
    name: 'Terminal vs. interfaz gráfica',
    speakerName: 'Jeremías Moreno Ivanoff',
    date: new Date('2021-04-24'),
    youtubeUrl: 'https://www.youtube.com/live/7F1m0PwHO38?si=t3l1Cggh5MpNiNJC&t=2171',
  },
  {
    name: 'Superando la facultad virtual con un equipo',
    speakerName: 'Gadiel Scharf y Tobías Paz Posse',
    date: new Date('2021-04-24'),
    youtubeUrl: 'https://www.youtube.com/live/7F1m0PwHO38?si=P85jvVZYQo-SqrE8&t=2971',
  },
  {
    name: 'Herramientas para el trabajo en equipo',
    speakerName: 'Gadiel Scharf y Tobías Paz Posse',
    date: new Date('2021-04-24'),
    youtubeUrl: 'https://www.youtube.com/live/7F1m0PwHO38?si=-IZyGVkqqYklvAZ5&t=3560',
  },
  {
    name: 'La visión sistémica en la programación',
    speakerName: 'Germán Navarro',
    date: new Date('2021-04-24'),
    youtubeUrl: 'https://www.youtube.com/live/7F1m0PwHO38?si=kf_zDIku8V-0wBaf&t=4350',
  },
  {
    name: 'El camino del programador',
    speakerName: 'Esteban Sánchez',
    date: new Date('2021-04-24'),
    youtubeUrl: 'https://www.youtube.com/live/7F1m0PwHO38?si=2Y61JSVvkAvzsNN9&t=5000',
  },
  {
    name: '¿Qué es Linux? ¿Qué es una distribución?',
    speakerName: 'Mauricio Sánchez',
    date: new Date('2020-11-28'),
    youtubeUrl: 'https://www.youtube.com/live/t41jcBED8y0?si=TRYJWUVIj_XAxaq3&t=214',
  },
  {
    name: '¿Por qué la gente le tiene miedo a Linux?',
    speakerName: 'Agustín Sánchez',
    date: new Date('2020-11-28'),
    youtubeUrl: 'https://www.youtube.com/live/t41jcBED8y0?si=lEiOYsrQDKkUwkMc&t=559',
  },
  {
    name: '¿Qué es un entorno de escritorio?',
    speakerName: 'Esteban Sánchez',
    date: new Date('2020-11-28'),
    youtubeUrl: 'https://www.youtube.com/live/t41jcBED8y0?si=s4ml8mAJTKJ413Ph&t=1284',
  },
  {
    name: 'One Line Linux',
    speakerName: 'Marcelo Nuñez',
    date: new Date('2020-11-28'),
    youtubeUrl: 'https://www.youtube.com/live/t41jcBED8y0?si=yXcElQHdNoBIFRUF&t=1530',
  },
  {
    name: 'Revisión de conceptos básicos de Git',
    speakerName: 'Agustín Sánchez',
    date: new Date('2020-10-24'),
    youtubeUrl: 'https://www.youtube.com/live/Nb0qN3x3Wfs?si=TvQENg_AF2Wro5f1&t=987',
  },
  {
    name: 'Sitios web para alojar repositorios de Git',
    speakerName: 'Iván Taddei',
    date: new Date('2020-10-24'),
    youtubeUrl: 'https://www.youtube.com/live/Nb0qN3x3Wfs?si=Nset4A1cy_o76QR4&t=2252',
  },
  {
    name: 'Creación de repositorio en GitHub y conexión a repositorio local',
    speakerName: 'Marcelo Núñez',
    date: new Date('2020-10-24'),
    youtubeUrl: 'https://www.youtube.com/live/Nb0qN3x3Wfs?si=FxBJof6AqcRWVCXf&t=2743',
  },
  {
    name: 'Clonación de repositorio de GitHub',
    speakerName: 'Agustín Lencina',
    date: new Date('2020-10-24'),
    youtubeUrl: 'https://www.youtube.com/live/Nb0qN3x3Wfs?si=Y_Dkqt1I8O1qmmqq&t=3694',
  },
  {
    name: 'Subida de cambios locales a repositorio de GitHub',
    speakerName: 'Esteban Sánchez',
    date: new Date('2020-10-24'),
    youtubeUrl: 'https://www.youtube.com/live/Nb0qN3x3Wfs?si=M4MUtBD-CW9XhX3z&t=4222',
  },
  {
    name: 'Trabajo en repositorios compartidos de GitHub',
    speakerName: 'Mauricio Sánchez',
    date: new Date('2020-10-24'),
    youtubeUrl: 'https://www.youtube.com/live/Nb0qN3x3Wfs?si=JjChJbKXI8nw2VXi&t=4772',
  },
  {
    name: 'Conflictos y su solución trabajando en equipo usando Git y GitHub',
    speakerName: 'Germán Navarro & Mauricio Sánchez',
    date: new Date('2020-10-24'),
    youtubeUrl: 'https://www.youtube.com/live/Nb0qN3x3Wfs?si=oIZvZoLA1vWjR7Lb&t=5551',
  },
  {
    name: 'Introducción conceptual a bases de datos',
    speakerName: 'Mauricio Sánchez',
    date: new Date('2020-09-19'),
    youtubeUrl: 'https://www.youtube.com/live/o-rHlSQHNEk?si=0eP6jjlNw-xfzw_W&t=1057',
  },
  {
    name: 'Introducción a las redes de computadoras',
    speakerName: 'Agustín Sánchez, Ivan Taddei & Marcelo Nuñez',
    date: new Date('2020-09-19'),
    youtubeUrl: 'https://www.youtube.com/live/o-rHlSQHNEk?si=w_Bh1R7asBNfLL09&t=1553',
  },
  {
    name: 'Redes en juegos online',
    speakerName: 'German Navarro',
    date: new Date('2020-09-19'),
    youtubeUrl: 'https://www.youtube.com/live/o-rHlSQHNEk?si=VPc2D5X-sbc_iN8u&t=2316',
  },
  {
    name: 'Sobrecarga vs Polimorfismo',
    speakerName: 'Facundo Gelatti',
    date: new Date('2020-09-19'),
    youtubeUrl: 'https://www.youtube.com/live/o-rHlSQHNEk?si=zXUtSGCEJBnflfIe&t=2808',
  },
  {
    name: '¿Qué son los puertos en redes informáticas?',
    speakerName: 'Agustín Lencina',
    date: new Date('2020-09-19'),
    youtubeUrl: 'https://www.youtube.com/live/o-rHlSQHNEk?si=zBEWxgpnEd8NaWM-&t=3620',
  },
  {
    name: 'Sistemas de gestión de bases de datos. Uso de comandos y ejemplos',
    speakerName: 'Franco Tarchini',
    date: new Date('2020-09-19'),
    youtubeUrl: 'https://www.youtube.com/live/o-rHlSQHNEk?si=1kuz4w_m-e27BYHx&t=4140',
  },
  {
    name: 'Búsqueda web y fuentes de información',
    speakerName: 'David Leila',
    date: new Date('2020-08-01'),
    youtubeUrl: 'https://www.youtube.com/live/cZiYoiNyVN0?si=NHQUbJAPLOJdlLba&t=5620s',
  },
  {
    name: 'Programación competitiva',
    speakerName: 'Esteban Sánchez & Iván Taddei',
    date: new Date('2020-08-01'),
    youtubeUrl: 'https://www.youtube.com/live/cZiYoiNyVN0?si=8ZMRFwhD3emaK01Y&t=3960',
  },
  {
    name: 'Filosofía del software: Charlando sobre software libre, privativo, código abierto, etc.',
    speakerName: 'Agustín Sánchez & Marcelo Nuñez',
    date: new Date('2020-08-01'),
    youtubeUrl: 'https://www.youtube.com/live/cZiYoiNyVN0?si=jHJbsyUeeKjLGWTN&t=1391',
  },
  {
    name: '¿De qué se trata la ingeniería en sistemas de información?',
    speakerName: 'Agustín Sánchez',
    date: new Date('2020-07-04'),
    youtubeUrl: 'https://www.youtube.com/live/L4RP34KjHns?si=fkbuYOhExaCzCzmY&t=632',
  },
  {
    name: 'Introducción al desarrollo de videojuegos con Godot Engine',
    speakerName: 'Germán Navarro',
    date: new Date('2020-07-04'),
    youtubeUrl: 'https://www.youtube.com/live/L4RP34KjHns?si=-IK0Gp2rTMTi2cxQ&t=2345',
  },
  {
    name: 'Funciones recursivas',
    speakerName: 'Esteban Sánchez',
    date: new Date('2020-07-04'),
    youtubeUrl: 'https://www.youtube.com/live/L4RP34KjHns?si=lZtUBr3TNpo-yYG6&t=3491',
  },
  {
    name: 'Aplicación insegura = desastre en el sistema operativo',
    speakerName: 'Marcelo Núñez',
    date: new Date('2020-07-04'),
    youtubeUrl: 'https://www.youtube.com/live/L4RP34KjHns?si=NxC6oQu8ZsMtEtDI&t=5255',
  },
  {
    name: 'DevOps, cultura y cambio',
    speakerName: 'Marco Canevaro',
    date: new Date('2020-07-04'),
    youtubeUrl: 'https://www.youtube.com/live/L4RP34KjHns?si=A4heB1QGNAJm9pJK&t=7045',
  },
  {
    name: 'Deno... y no es sólo un acrónimo de Node',
    speakerName: 'Agustín Lencina',
    date: new Date('2020-07-04'),
    youtubeUrl: 'https://www.youtube.com/live/L4RP34KjHns?si=lGkJ9ClsGH9NxM5G&t=7890',
  },
  {
    name: 'Patrón de diseño orientado a objetos "Observer"',
    speakerName: 'Mauricio Sánchez',
    date: new Date('2020-07-04'),
    youtubeUrl: 'https://www.youtube.com/live/L4RP34KjHns?si=NRFGpSTE7D0VWJvw&t=9400',
  },
  {
    name: 'Una mirada a la industria del software',
    date: new Date('2023-11-24'),
    speakerName: 'Agustín Sánchez & Marcelo Nuñez',
    portrait: '/una-mirada-a-la-industria-del-software.jpeg',
    location: 'Mercado de Tafí Viejo (Tucumán, Argentina)',
    slides: [
      '/charla-industria-software-24-11-2024/001.jpeg',
      '/charla-industria-software-24-11-2024/002.jpeg',
      '/charla-industria-software-24-11-2024/003.jpeg',
      '/charla-industria-software-24-11-2024/004.jpeg',
      '/charla-industria-software-24-11-2024/005.jpeg',
      '/charla-industria-software-24-11-2024/006.jpeg',
      '/charla-industria-software-24-11-2024/007.jpeg',
      '/charla-industria-software-24-11-2024/008.jpeg',
      '/charla-industria-software-24-11-2024/009.jpeg',
      '/charla-industria-software-24-11-2024/010.jpeg',
      '/charla-industria-software-24-11-2024/011.jpeg',
      '/charla-industria-software-24-11-2024/012.jpeg',
      '/charla-industria-software-24-11-2024/013.jpeg',
      '/charla-industria-software-24-11-2024/014.jpeg',
      '/charla-industria-software-24-11-2024/015.jpeg',
      '/charla-industria-software-24-11-2024/016.jpeg',
      '/charla-industria-software-24-11-2024/017.jpeg',
      '/charla-industria-software-24-11-2024/018.jpeg',
      '/charla-industria-software-24-11-2024/019.jpeg',
      '/charla-industria-software-24-11-2024/020.jpeg',
    ],
  },
  {
    name: 'Arquitectura de software: fundamentos, experiencias y recomendaciones',
    date: new Date('2023-10-04'),
    speakerName: 'Agustín Sánchez',
    portrait: '/agus-charla-global-learning-1.jpeg',
    location: 'Alter City Business Park (Tucumán, Argentina)',
  },
];
