-- AlterTable
ALTER TABLE "Event" ADD COLUMN     "coverFocusX" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "coverFocusY" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "coverZoom" INTEGER NOT NULL DEFAULT 100;
