// Generated by scripts/generate-db-schema.mjs from prisma/schema.prisma — don't edit by hand.

export type DbField = {
  name: string;
  type: string;
  pk?: boolean;
  fk?: boolean;
  unique?: boolean;
  optional?: boolean;
  list?: boolean;
};

export type DbModel = {
  name: string;
  domain: DbDomain;
  fields: DbField[];
  /** Composite unique constraints (`@@unique`). */
  uniques: string[][];
};

/** A foreign key: `from` holds it and points at `to`. `many`: `to` has many `from`. */
export type DbRelation = {
  from: string;
  to: string;
  label: string;
  optional: boolean;
  many: boolean;
  onDelete: string | null;
};

export type DbDomain =
  'comunidad' | 'consejos' | 'eventos' | 'charlas' | 'galeria' | 'proyectos' | 'auth' | 'sistema';

export const DB_SCHEMA_UPDATED_AT = '2026-10-07';

export const dbEnums: { name: string; values: string[] }[] = [
  {
    name: 'Role',
    values: ['REGULAR', 'ADMIN'],
  },
  {
    name: 'GalleryItemKind',
    values: ['PHOTO', 'VIDEO'],
  },
  {
    name: 'TalkProposalStatus',
    values: ['PENDING', 'ACCEPTED', 'REJECTED'],
  },
];

export const dbModels: DbModel[] = [
  {
    name: 'User',
    domain: 'comunidad',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'name',
        type: 'String',
      },
      {
        name: 'email',
        type: 'String',
        unique: true,
      },
      {
        name: 'password',
        type: 'String',
      },
      {
        name: 'emailVerified',
        type: 'Boolean',
      },
      {
        name: 'phoneNumber',
        type: 'String',
        optional: true,
      },
      {
        name: 'role',
        type: 'Role',
      },
      {
        name: 'isAmbassador',
        type: 'Boolean',
      },
      {
        name: 'isCofounder',
        type: 'Boolean',
      },
      {
        name: 'image',
        type: 'String',
        optional: true,
      },
      {
        name: 'countryOfOrigin',
        type: 'String',
        optional: true,
      },
      {
        name: 'province',
        type: 'String',
        optional: true,
      },
      {
        name: 'xAccountUrl',
        type: 'String',
        optional: true,
      },
      {
        name: 'linkedinUrl',
        type: 'String',
        optional: true,
      },
      {
        name: 'gitHubUrl',
        type: 'String',
        optional: true,
      },
      {
        name: 'instagramUrl',
        type: 'String',
        optional: true,
      },
      {
        name: 'youtubeUrl',
        type: 'String',
        optional: true,
      },
      {
        name: 'twitchUrl',
        type: 'String',
        optional: true,
      },
      {
        name: 'kickUrl',
        type: 'String',
        optional: true,
      },
      {
        name: 'slogan',
        type: 'String',
        optional: true,
      },
      {
        name: 'jobTitle',
        type: 'String',
        optional: true,
      },
      {
        name: 'enterprise',
        type: 'String',
        optional: true,
      },
      {
        name: 'career',
        type: 'String',
        optional: true,
      },
      {
        name: 'studyPlace',
        type: 'String',
        optional: true,
      },
      {
        name: 'specialties',
        type: 'String',
        list: true,
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
      {
        name: 'updatedAt',
        type: 'DateTime',
      },
    ],
    uniques: [],
  },
  {
    name: 'UserPosition',
    domain: 'comunidad',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'userId',
        type: 'String',
        fk: true,
      },
      {
        name: 'jobTitle',
        type: 'String',
      },
      {
        name: 'enterprise',
        type: 'String',
        optional: true,
      },
      {
        name: 'order',
        type: 'Int',
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
    ],
    uniques: [],
  },
  {
    name: 'Session',
    domain: 'auth',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'userId',
        type: 'String',
        fk: true,
      },
      {
        name: 'expires',
        type: 'DateTime',
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
      {
        name: 'updatedAt',
        type: 'DateTime',
      },
    ],
    uniques: [],
  },
  {
    name: 'Advise',
    domain: 'consejos',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'content',
        type: 'String',
      },
      {
        name: 'authorId',
        type: 'String',
        fk: true,
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
      {
        name: 'updatedAt',
        type: 'DateTime',
      },
    ],
    uniques: [],
  },
  {
    name: 'Comment',
    domain: 'consejos',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'content',
        type: 'String',
      },
      {
        name: 'authorId',
        type: 'String',
        fk: true,
      },
      {
        name: 'adviseId',
        type: 'String',
        fk: true,
      },
      {
        name: 'parentCommentId',
        type: 'String',
        fk: true,
        optional: true,
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
      {
        name: 'updatedAt',
        type: 'DateTime',
      },
    ],
    uniques: [],
  },
  {
    name: 'UserLanguage',
    domain: 'comunidad',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'userId',
        type: 'String',
        fk: true,
      },
      {
        name: 'language',
        type: 'String',
      },
      {
        name: 'color',
        type: 'String',
      },
      {
        name: 'logo',
        type: 'String',
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
      {
        name: 'updatedAt',
        type: 'DateTime',
      },
    ],
    uniques: [],
  },
  {
    name: 'Event',
    domain: 'eventos',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'date',
        type: 'DateTime',
      },
      {
        name: 'endDate',
        type: 'DateTime',
        optional: true,
      },
      {
        name: 'name',
        type: 'String',
      },
      {
        name: 'description',
        type: 'String',
      },
      {
        name: 'city',
        type: 'String',
        optional: true,
      },
      {
        name: 'address',
        type: 'String',
        optional: true,
      },
      {
        name: 'placeName',
        type: 'String',
        optional: true,
      },
      {
        name: 'flyerImages',
        type: 'String',
        list: true,
      },
      {
        name: 'googleMapsUrl',
        type: 'String',
        optional: true,
      },
      {
        name: 'capacity',
        type: 'Int',
        optional: true,
      },
      {
        name: 'externalRegistrationUrl',
        type: 'String',
        optional: true,
      },
      {
        name: 'markedAsFull',
        type: 'Boolean',
      },
      {
        name: 'callForSpeakersEnabled',
        type: 'Boolean',
      },
      {
        name: 'isOnline',
        type: 'Boolean',
      },
      {
        name: 'streamingUrl',
        type: 'String',
        optional: true,
      },
      {
        name: 'shortcut',
        type: 'String',
        optional: true,
      },
      {
        name: 'coverPhotoId',
        type: 'String',
        fk: true,
        unique: true,
        optional: true,
      },
      {
        name: 'coverFocusX',
        type: 'Int',
      },
      {
        name: 'coverFocusY',
        type: 'Int',
      },
      {
        name: 'coverZoom',
        type: 'Int',
      },
      {
        name: 'deletedAt',
        type: 'DateTime',
        optional: true,
      },
      {
        name: 'createdById',
        type: 'String',
        fk: true,
        optional: true,
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
      {
        name: 'updatedAt',
        type: 'DateTime',
      },
    ],
    uniques: [],
  },
  {
    name: 'EventOrganizer',
    domain: 'eventos',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'eventId',
        type: 'String',
        fk: true,
      },
      {
        name: 'userId',
        type: 'String',
        fk: true,
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
    ],
    uniques: [['eventId', 'userId']],
  },
  {
    name: 'GalleryItem',
    domain: 'galeria',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'kind',
        type: 'GalleryItemKind',
      },
      {
        name: 'src',
        type: 'String',
      },
      {
        name: 'thumbSrc',
        type: 'String',
      },
      {
        name: 'mimeType',
        type: 'String',
        optional: true,
      },
      {
        name: 'durationSeconds',
        type: 'Int',
        optional: true,
      },
      {
        name: 'width',
        type: 'Int',
        optional: true,
      },
      {
        name: 'height',
        type: 'Int',
        optional: true,
      },
      {
        name: 'storageKeys',
        type: 'String',
        list: true,
      },
      {
        name: 'takenAt',
        type: 'DateTime',
      },
      {
        name: 'description',
        type: 'String',
        optional: true,
      },
      {
        name: 'eventId',
        type: 'String',
        fk: true,
        optional: true,
      },
      {
        name: 'uploadedById',
        type: 'String',
        fk: true,
        optional: true,
      },
      {
        name: 'legacyId',
        type: 'Int',
        unique: true,
        optional: true,
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
      {
        name: 'updatedAt',
        type: 'DateTime',
      },
    ],
    uniques: [],
  },
  {
    name: 'GalleryItemTag',
    domain: 'galeria',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'itemId',
        type: 'String',
        fk: true,
      },
      {
        name: 'userId',
        type: 'String',
        fk: true,
      },
      {
        name: 'taggedById',
        type: 'String',
        fk: true,
        optional: true,
      },
      {
        name: 'x',
        type: 'Float',
        optional: true,
      },
      {
        name: 'y',
        type: 'Float',
        optional: true,
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
    ],
    uniques: [['itemId', 'userId']],
  },
  {
    name: 'Setup',
    domain: 'comunidad',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'title',
        type: 'String',
      },
      {
        name: 'description',
        type: 'String',
      },
      {
        name: 'imageUrl',
        type: 'String',
      },
      {
        name: 'thumbUrl',
        type: 'String',
      },
      {
        name: 'width',
        type: 'Int',
      },
      {
        name: 'height',
        type: 'Int',
      },
      {
        name: 'storageKeys',
        type: 'String',
        list: true,
      },
      {
        name: 'authorId',
        type: 'String',
        fk: true,
      },
      {
        name: 'date',
        type: 'DateTime',
      },
      {
        name: 'os',
        type: 'String',
        optional: true,
      },
      {
        name: 'browser',
        type: 'String',
        optional: true,
      },
      {
        name: 'editor',
        type: 'String',
        optional: true,
      },
      {
        name: 'terminal',
        type: 'String',
        optional: true,
      },
      {
        name: 'otherSoftware',
        type: 'String',
        optional: true,
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
      {
        name: 'updatedAt',
        type: 'DateTime',
      },
    ],
    uniques: [],
  },
  {
    name: 'SetupLike',
    domain: 'comunidad',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'userId',
        type: 'String',
        fk: true,
      },
      {
        name: 'setupId',
        type: 'String',
        fk: true,
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
    ],
    uniques: [['setupId', 'userId']],
  },
  {
    name: 'Like',
    domain: 'consejos',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'userId',
        type: 'String',
        fk: true,
      },
      {
        name: 'adviseId',
        type: 'String',
        fk: true,
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
      {
        name: 'updatedAt',
        type: 'DateTime',
      },
    ],
    uniques: [['userId', 'adviseId']],
  },
  {
    name: 'JobOffers',
    domain: 'sistema',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'title',
        type: 'String',
      },
      {
        name: 'description',
        type: 'String',
      },
      {
        name: 'company',
        type: 'String',
      },
      {
        name: 'available',
        type: 'Boolean',
      },
      {
        name: 'tags',
        type: 'String',
        list: true,
      },
      {
        name: 'location',
        type: 'String',
      },
      {
        name: 'type',
        type: 'String',
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
      {
        name: 'updatedAt',
        type: 'DateTime',
      },
    ],
    uniques: [],
  },
  {
    name: 'Announcement',
    domain: 'eventos',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'title',
        type: 'String',
      },
      {
        name: 'content',
        type: 'String',
      },
      {
        name: 'category',
        type: 'String',
      },
      {
        name: 'pinned',
        type: 'Boolean',
      },
      {
        name: 'published',
        type: 'Boolean',
      },
      {
        name: 'authorId',
        type: 'String',
        fk: true,
      },
      {
        name: 'eventId',
        type: 'String',
        fk: true,
        optional: true,
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
      {
        name: 'updatedAt',
        type: 'DateTime',
      },
    ],
    uniques: [],
  },
  {
    name: 'EventRegistration',
    domain: 'eventos',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'eventId',
        type: 'String',
        fk: true,
      },
      {
        name: 'userId',
        type: 'String',
        fk: true,
      },
      {
        name: 'cancelledAt',
        type: 'DateTime',
        optional: true,
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
      {
        name: 'updatedAt',
        type: 'DateTime',
      },
    ],
    uniques: [['eventId', 'userId']],
  },
  {
    name: 'EventWaitlistEntry',
    domain: 'eventos',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'eventId',
        type: 'String',
        fk: true,
      },
      {
        name: 'userId',
        type: 'String',
        fk: true,
      },
      {
        name: 'cancelledAt',
        type: 'DateTime',
        optional: true,
      },
      {
        name: 'promotedAt',
        type: 'DateTime',
        optional: true,
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
      {
        name: 'updatedAt',
        type: 'DateTime',
      },
    ],
    uniques: [['eventId', 'userId']],
  },
  {
    name: 'EventBroadcast',
    domain: 'eventos',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'eventId',
        type: 'String',
        fk: true,
      },
      {
        name: 'authorId',
        type: 'String',
        fk: true,
        optional: true,
      },
      {
        name: 'audience',
        type: 'String',
      },
      {
        name: 'subject',
        type: 'String',
      },
      {
        name: 'message',
        type: 'String',
      },
      {
        name: 'recipients',
        type: 'Int',
      },
      {
        name: 'failed',
        type: 'Int',
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
    ],
    uniques: [],
  },
  {
    name: 'EventFlyerDesigner',
    domain: 'eventos',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'eventId',
        type: 'String',
        fk: true,
      },
      {
        name: 'flyerSrc',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
        fk: true,
        optional: true,
      },
      {
        name: 'name',
        type: 'String',
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
    ],
    uniques: [],
  },
  {
    name: 'Sponsor',
    domain: 'eventos',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'eventId',
        type: 'String',
        fk: true,
      },
      {
        name: 'name',
        type: 'String',
      },
      {
        name: 'website',
        type: 'String',
        optional: true,
      },
      {
        name: 'logo',
        type: 'String',
        optional: true,
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
      {
        name: 'updatedAt',
        type: 'DateTime',
      },
    ],
    uniques: [],
  },
  {
    name: 'PageVisit',
    domain: 'sistema',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'path',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
        fk: true,
        optional: true,
      },
      {
        name: 'ipAddress',
        type: 'String',
        optional: true,
      },
      {
        name: 'userAgent',
        type: 'String',
        optional: true,
      },
      {
        name: 'referer',
        type: 'String',
        optional: true,
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
    ],
    uniques: [],
  },
  {
    name: 'Testimonial',
    domain: 'comunidad',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'body',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
        fk: true,
      },
      {
        name: 'featured',
        type: 'Boolean',
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
      {
        name: 'updatedAt',
        type: 'DateTime',
      },
    ],
    uniques: [],
  },
  {
    name: 'Notification',
    domain: 'comunidad',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'type',
        type: 'String',
      },
      {
        name: 'title',
        type: 'String',
      },
      {
        name: 'message',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
        fk: true,
        optional: true,
      },
      {
        name: 'read',
        type: 'Boolean',
      },
      {
        name: 'metadata',
        type: 'String',
        optional: true,
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
    ],
    uniques: [],
  },
  {
    name: 'ErrorLog',
    domain: 'sistema',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'message',
        type: 'String',
      },
      {
        name: 'stack',
        type: 'String',
        optional: true,
      },
      {
        name: 'path',
        type: 'String',
        optional: true,
      },
      {
        name: 'userId',
        type: 'String',
        fk: true,
        optional: true,
      },
      {
        name: 'userAgent',
        type: 'String',
        optional: true,
      },
      {
        name: 'ipAddress',
        type: 'String',
        optional: true,
      },
      {
        name: 'metadata',
        type: 'String',
        optional: true,
      },
      {
        name: 'resolved',
        type: 'Boolean',
      },
      {
        name: 'resolvedAt',
        type: 'DateTime',
        optional: true,
      },
      {
        name: 'resolvedBy',
        type: 'String',
        fk: true,
        optional: true,
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
    ],
    uniques: [],
  },
  {
    name: 'AppLog',
    domain: 'sistema',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'level',
        type: 'String',
      },
      {
        name: 'message',
        type: 'String',
      },
      {
        name: 'path',
        type: 'String',
        optional: true,
      },
      {
        name: 'userId',
        type: 'String',
        fk: true,
        optional: true,
      },
      {
        name: 'userAgent',
        type: 'String',
        optional: true,
      },
      {
        name: 'ipAddress',
        type: 'String',
        optional: true,
      },
      {
        name: 'metadata',
        type: 'String',
        optional: true,
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
    ],
    uniques: [],
  },
  {
    name: 'PasswordResetToken',
    domain: 'auth',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'email',
        type: 'String',
      },
      {
        name: 'code',
        type: 'String',
      },
      {
        name: 'expiresAt',
        type: 'DateTime',
      },
      {
        name: 'used',
        type: 'Boolean',
      },
      {
        name: 'attempts',
        type: 'Int',
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
    ],
    uniques: [],
  },
  {
    name: 'EmailVerificationToken',
    domain: 'auth',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'email',
        type: 'String',
      },
      {
        name: 'code',
        type: 'String',
      },
      {
        name: 'expiresAt',
        type: 'DateTime',
      },
      {
        name: 'used',
        type: 'Boolean',
      },
      {
        name: 'attempts',
        type: 'Int',
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
    ],
    uniques: [],
  },
  {
    name: 'TalkProposal',
    domain: 'charlas',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'eventId',
        type: 'String',
        fk: true,
      },
      {
        name: 'userId',
        type: 'String',
        fk: true,
      },
      {
        name: 'title',
        type: 'String',
      },
      {
        name: 'description',
        type: 'String',
      },
      {
        name: 'status',
        type: 'TalkProposalStatus',
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
      {
        name: 'updatedAt',
        type: 'DateTime',
      },
    ],
    uniques: [],
  },
  {
    name: 'TalkProposalSpeaker',
    domain: 'charlas',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'talkProposalId',
        type: 'String',
        fk: true,
      },
      {
        name: 'userId',
        type: 'String',
        fk: true,
        optional: true,
      },
      {
        name: 'speakerName',
        type: 'String',
      },
      {
        name: 'speakerPhone',
        type: 'String',
      },
      {
        name: 'isProfessional',
        type: 'Boolean',
      },
      {
        name: 'jobTitle',
        type: 'String',
        optional: true,
      },
      {
        name: 'enterprise',
        type: 'String',
        optional: true,
      },
      {
        name: 'isStudent',
        type: 'Boolean',
      },
      {
        name: 'career',
        type: 'String',
        optional: true,
      },
      {
        name: 'studyPlace',
        type: 'String',
        optional: true,
      },
      {
        name: 'order',
        type: 'Int',
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
      {
        name: 'updatedAt',
        type: 'DateTime',
      },
    ],
    uniques: [],
  },
  {
    name: 'Talk',
    domain: 'charlas',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'eventId',
        type: 'String',
        fk: true,
        optional: true,
      },
      {
        name: 'proposalId',
        type: 'String',
        fk: true,
        unique: true,
        optional: true,
      },
      {
        name: 'title',
        type: 'String',
      },
      {
        name: 'description',
        type: 'String',
      },
      {
        name: 'manualEventTitle',
        type: 'String',
        optional: true,
      },
      {
        name: 'manualEventDate',
        type: 'DateTime',
        optional: true,
      },
      {
        name: 'manualEventLocation',
        type: 'String',
        optional: true,
      },
      {
        name: 'order',
        type: 'Int',
      },
      {
        name: 'portraitUrl',
        type: 'String',
        optional: true,
      },
      {
        name: 'slidesUrl',
        type: 'String',
        optional: true,
      },
      {
        name: 'slideImages',
        type: 'String',
        list: true,
      },
      {
        name: 'videoUrl',
        type: 'String',
        optional: true,
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
      {
        name: 'updatedAt',
        type: 'DateTime',
      },
    ],
    uniques: [],
  },
  {
    name: 'TalkSpeaker',
    domain: 'charlas',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'talkId',
        type: 'String',
        fk: true,
      },
      {
        name: 'userId',
        type: 'String',
        fk: true,
        optional: true,
      },
      {
        name: 'speakerName',
        type: 'String',
      },
      {
        name: 'speakerPhone',
        type: 'String',
      },
      {
        name: 'isProfessional',
        type: 'Boolean',
      },
      {
        name: 'jobTitle',
        type: 'String',
        optional: true,
      },
      {
        name: 'enterprise',
        type: 'String',
        optional: true,
      },
      {
        name: 'isStudent',
        type: 'Boolean',
      },
      {
        name: 'career',
        type: 'String',
        optional: true,
      },
      {
        name: 'studyPlace',
        type: 'String',
        optional: true,
      },
      {
        name: 'order',
        type: 'Int',
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
      {
        name: 'updatedAt',
        type: 'DateTime',
      },
    ],
    uniques: [],
  },
  {
    name: 'Project',
    domain: 'proyectos',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'title',
        type: 'String',
      },
      {
        name: 'description',
        type: 'String',
      },
      {
        name: 'url',
        type: 'String',
      },
      {
        name: 'logoUrl',
        type: 'String',
      },
      {
        name: 'techStack',
        type: 'String',
        list: true,
      },
      {
        name: 'order',
        type: 'Int',
      },
      {
        name: 'isOpenSource',
        type: 'Boolean',
      },
      {
        name: 'repoUrl',
        type: 'String',
        optional: true,
      },
      {
        name: 'startYear',
        type: 'Int',
        optional: true,
      },
      {
        name: 'endYear',
        type: 'Int',
        optional: true,
      },
      {
        name: 'authorId',
        type: 'String',
        fk: true,
        optional: true,
      },
      {
        name: 'authorRole',
        type: 'String',
        optional: true,
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
      {
        name: 'updatedAt',
        type: 'DateTime',
      },
    ],
    uniques: [],
  },
  {
    name: 'ProjectMember',
    domain: 'proyectos',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'projectId',
        type: 'String',
        fk: true,
      },
      {
        name: 'userId',
        type: 'String',
        fk: true,
        optional: true,
      },
      {
        name: 'memberName',
        type: 'String',
      },
      {
        name: 'role',
        type: 'String',
        optional: true,
      },
      {
        name: 'order',
        type: 'Int',
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
      {
        name: 'updatedAt',
        type: 'DateTime',
      },
    ],
    uniques: [],
  },
  {
    name: 'ContentMark',
    domain: 'comunidad',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'userId',
        type: 'String',
        fk: true,
      },
      {
        name: 'contentType',
        type: 'String',
      },
      {
        name: 'contentId',
        type: 'String',
      },
      {
        name: 'mark',
        type: 'String',
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
    ],
    uniques: [['userId', 'contentType', 'contentId', 'mark']],
  },
  {
    name: 'IdentityLink',
    domain: 'comunidad',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'source',
        type: 'String',
      },
      {
        name: 'externalName',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
        fk: true,
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
      {
        name: 'updatedAt',
        type: 'DateTime',
      },
    ],
    uniques: [['source', 'externalName']],
  },
  {
    name: 'Badge',
    domain: 'comunidad',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'name',
        type: 'String',
      },
      {
        name: 'description',
        type: 'String',
      },
      {
        name: 'icon',
        type: 'String',
      },
      {
        name: 'tone',
        type: 'String',
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
      {
        name: 'updatedAt',
        type: 'DateTime',
      },
    ],
    uniques: [],
  },
  {
    name: 'UserBadge',
    domain: 'comunidad',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'userId',
        type: 'String',
        fk: true,
      },
      {
        name: 'badgeId',
        type: 'String',
        fk: true,
      },
      {
        name: 'awardedById',
        type: 'String',
        fk: true,
        optional: true,
      },
      {
        name: 'awardedAt',
        type: 'DateTime',
      },
    ],
    uniques: [['userId', 'badgeId']],
  },
  {
    name: 'ArticleAuthor',
    domain: 'proyectos',
    fields: [
      {
        name: 'id',
        type: 'String',
        pk: true,
      },
      {
        name: 'articleId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
        fk: true,
      },
      {
        name: 'addedById',
        type: 'String',
        fk: true,
        optional: true,
      },
      {
        name: 'createdAt',
        type: 'DateTime',
      },
    ],
    uniques: [['articleId', 'userId']],
  },
];

export const dbRelations: DbRelation[] = [
  {
    from: 'UserPosition',
    to: 'User',
    label: 'user',
    optional: false,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'Session',
    to: 'User',
    label: 'user',
    optional: false,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'Advise',
    to: 'User',
    label: 'author',
    optional: false,
    many: true,
    onDelete: null,
  },
  {
    from: 'Comment',
    to: 'User',
    label: 'author',
    optional: false,
    many: true,
    onDelete: null,
  },
  {
    from: 'Comment',
    to: 'Advise',
    label: 'advise',
    optional: false,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'Comment',
    to: 'Comment',
    label: 'parentComment',
    optional: true,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'UserLanguage',
    to: 'User',
    label: 'user',
    optional: false,
    many: true,
    onDelete: null,
  },
  {
    from: 'Event',
    to: 'User',
    label: 'createdBy',
    optional: true,
    many: true,
    onDelete: 'SetNull',
  },
  {
    from: 'Event',
    to: 'GalleryItem',
    label: 'coverPhoto',
    optional: true,
    many: false,
    onDelete: 'SetNull',
  },
  {
    from: 'EventOrganizer',
    to: 'Event',
    label: 'event',
    optional: false,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'EventOrganizer',
    to: 'User',
    label: 'user',
    optional: false,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'GalleryItem',
    to: 'Event',
    label: 'event',
    optional: true,
    many: true,
    onDelete: 'SetNull',
  },
  {
    from: 'GalleryItem',
    to: 'User',
    label: 'uploadedBy',
    optional: true,
    many: true,
    onDelete: 'SetNull',
  },
  {
    from: 'GalleryItemTag',
    to: 'GalleryItem',
    label: 'item',
    optional: false,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'GalleryItemTag',
    to: 'User',
    label: 'user',
    optional: false,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'GalleryItemTag',
    to: 'User',
    label: 'taggedBy',
    optional: true,
    many: true,
    onDelete: 'SetNull',
  },
  {
    from: 'Setup',
    to: 'User',
    label: 'author',
    optional: false,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'SetupLike',
    to: 'User',
    label: 'user',
    optional: false,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'SetupLike',
    to: 'Setup',
    label: 'setup',
    optional: false,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'Like',
    to: 'User',
    label: 'user',
    optional: false,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'Like',
    to: 'Advise',
    label: 'advise',
    optional: false,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'Announcement',
    to: 'User',
    label: 'author',
    optional: false,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'Announcement',
    to: 'Event',
    label: 'event',
    optional: true,
    many: true,
    onDelete: 'SetNull',
  },
  {
    from: 'EventRegistration',
    to: 'Event',
    label: 'event',
    optional: false,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'EventRegistration',
    to: 'User',
    label: 'user',
    optional: false,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'EventWaitlistEntry',
    to: 'Event',
    label: 'event',
    optional: false,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'EventWaitlistEntry',
    to: 'User',
    label: 'user',
    optional: false,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'EventBroadcast',
    to: 'Event',
    label: 'event',
    optional: false,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'EventBroadcast',
    to: 'User',
    label: 'author',
    optional: true,
    many: true,
    onDelete: 'SetNull',
  },
  {
    from: 'EventFlyerDesigner',
    to: 'Event',
    label: 'event',
    optional: false,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'EventFlyerDesigner',
    to: 'User',
    label: 'user',
    optional: true,
    many: true,
    onDelete: 'SetNull',
  },
  {
    from: 'Sponsor',
    to: 'Event',
    label: 'event',
    optional: false,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'PageVisit',
    to: 'User',
    label: 'user',
    optional: true,
    many: true,
    onDelete: 'SetNull',
  },
  {
    from: 'Testimonial',
    to: 'User',
    label: 'user',
    optional: false,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'Notification',
    to: 'User',
    label: 'user',
    optional: true,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'ErrorLog',
    to: 'User',
    label: 'user',
    optional: true,
    many: true,
    onDelete: 'SetNull',
  },
  {
    from: 'ErrorLog',
    to: 'User',
    label: 'resolver',
    optional: true,
    many: true,
    onDelete: 'SetNull',
  },
  {
    from: 'AppLog',
    to: 'User',
    label: 'user',
    optional: true,
    many: true,
    onDelete: 'SetNull',
  },
  {
    from: 'TalkProposal',
    to: 'Event',
    label: 'event',
    optional: false,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'TalkProposal',
    to: 'User',
    label: 'user',
    optional: false,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'TalkProposalSpeaker',
    to: 'TalkProposal',
    label: 'talkProposal',
    optional: false,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'TalkProposalSpeaker',
    to: 'User',
    label: 'user',
    optional: true,
    many: true,
    onDelete: 'SetNull',
  },
  {
    from: 'Talk',
    to: 'Event',
    label: 'event',
    optional: true,
    many: true,
    onDelete: 'SetNull',
  },
  {
    from: 'Talk',
    to: 'TalkProposal',
    label: 'proposal',
    optional: true,
    many: false,
    onDelete: 'SetNull',
  },
  {
    from: 'TalkSpeaker',
    to: 'Talk',
    label: 'talk',
    optional: false,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'TalkSpeaker',
    to: 'User',
    label: 'user',
    optional: true,
    many: true,
    onDelete: 'SetNull',
  },
  {
    from: 'Project',
    to: 'User',
    label: 'author',
    optional: true,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'ProjectMember',
    to: 'Project',
    label: 'project',
    optional: false,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'ProjectMember',
    to: 'User',
    label: 'user',
    optional: true,
    many: true,
    onDelete: 'SetNull',
  },
  {
    from: 'ContentMark',
    to: 'User',
    label: 'user',
    optional: false,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'IdentityLink',
    to: 'User',
    label: 'user',
    optional: false,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'UserBadge',
    to: 'User',
    label: 'user',
    optional: false,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'UserBadge',
    to: 'Badge',
    label: 'badge',
    optional: false,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'UserBadge',
    to: 'User',
    label: 'awardedBy',
    optional: true,
    many: true,
    onDelete: 'SetNull',
  },
  {
    from: 'ArticleAuthor',
    to: 'User',
    label: 'user',
    optional: false,
    many: true,
    onDelete: 'Cascade',
  },
  {
    from: 'ArticleAuthor',
    to: 'User',
    label: 'addedBy',
    optional: true,
    many: true,
    onDelete: 'SetNull',
  },
];
