import type { InterviewGuide } from './types';

export const qaGuide: InterviewGuide = {
  track: 'qa',
  summary:
    'Guía de quality engineering para entrevistas: fundamentos, diseño de casos, bugs, APIs, estrategia, automatización con Cypress y Playwright y performance con k6.',
  sections: [
    {
      id: 'la-entrevista',
      title: 'Cómo es la entrevista',
      body: [
        'Una entrevista de QA suele tener preguntas de fundamentos, un ejercicio de diseño de casos (te dan un formulario, una pantalla o un endpoint y tenés que decir qué probarías), preguntas sobre bugs y proceso, y, si el rol incluye automatización, una parte técnica con la herramienta que usa el equipo: código en vivo, revisión de un test existente o un take-home.',
        'En junior se espera que domines los conceptos (niveles y tipos de testing, regresión, smoke), técnicas básicas como particiones de equivalencia y valores límite, que sepas escribir un caso de prueba y un reporte de bug claros, y que te manejes con Postman y SQL básico. Si es un rol de automatización, que escribas un test simple con buenos selectores y aserciones.',
        'En semi-senior el foco pasa a priorizar con poco tiempo, aplicar técnicas más avanzadas (tablas de decisión, transición de estados, pairwise), escribir criterios de aceptación, trabajar en un equipo ágil y, en automatización, manejar flaky tests, datos de prueba, mocks y CI.',
        'En senior evalúan estrategia: cómo armar calidad en una organización, pirámide de testing, quality gates, métricas, testing en producción, microservicios, testing no funcional y cómo justificar la inversión. También cómo influís en el equipo para que la calidad sea de todos y no solo de QA.',
      ],
      checklist: [
        'Explicar qué evalúan en cada seniority',
        'Saber si el rol es manual, automatizado o mixto y con qué herramientas',
        'Contar en 2 minutos tu experiencia y un bug importante que encontraste',
        'Tener ejemplos concretos de casos de prueba y reportes que escribiste',
        'Conocer el producto de la empresa lo suficiente para opinar qué probarías',
      ],
    },
    {
      id: 'fundamentos',
      title: 'Fundamentos del testing',
      body: [
        'Distinguí bien los conceptos: QA es el proceso para prevenir defectos, QC es verificar el producto y testing es la actividad de ejecutar pruebas. Un error es una equivocación humana, que produce un defecto en el código, que puede manifestarse como una falla al ejecutarse. Verificación es "¿lo construimos bien?" (contra la especificación) y validación es "¿construimos lo correcto?" (contra la necesidad del usuario).',
        'Los niveles de testing son unitario, integración, sistema y aceptación (UAT, que hacen usuarios o negocio). Los tipos se dividen en funcionales (qué hace el sistema) y no funcionales (cómo lo hace: performance, seguridad, usabilidad, accesibilidad, compatibilidad). Caja negra prueba desde afuera sin mirar el código; caja blanca usa el conocimiento de la implementación, por ejemplo para cubrir ramas.',
        'Smoke testing es una verificación rápida y amplia de que lo crítico funciona tras un build; sanity es una verificación acotada y profunda de un cambio puntual; regresión confirma que lo que funcionaba sigue funcionando después de un cambio. El STLC ordena el trabajo: análisis de requisitos, planificación, diseño de casos, preparación del entorno, ejecución y cierre.',
        'Probar todo es imposible: la combinación de entradas, estados y entornos es prácticamente infinita. Por eso el testing se basa en riesgo y técnicas de diseño, y por eso "no encontré bugs" no significa "no hay bugs". Los entrevistadores valoran que expliques los conceptos con ejemplos propios en vez de recitar definiciones de un glosario.',
      ],
      checklist: [
        'Diferenciar QA, QC y testing con un ejemplo',
        'Explicar error, defecto y falla',
        'Nombrar los niveles de testing y quién hace cada uno',
        'Diferenciar smoke, sanity y regresión',
        'Explicar verificación contra validación y caja negra contra caja blanca',
        'Describir las fases del STLC',
      ],
    },
    {
      id: 'diseno-de-casos',
      title: 'Diseño de casos de prueba',
      body: [
        'Las particiones de equivalencia dividen las entradas en grupos que el sistema debería tratar igual, y probás un valor por grupo, incluidos los inválidos. El análisis de valores límite prueba los bordes, donde se concentran los errores: para un campo de 1 a 100, probás 0, 1, 2, 99, 100 y 101. Usalas juntas y explicá en voz alta qué grupos encontraste.',
        'Las tablas de decisión sirven cuando el resultado depende de combinaciones de condiciones (descuentos, permisos, reglas de negocio): cada columna es una combinación con su resultado esperado. La transición de estados modela un objeto que cambia de estado (un pedido: creado, pagado, enviado, entregado, cancelado) y prueba transiciones válidas e inválidas. Pairwise reduce combinaciones de muchos parámetros probando todos los pares posibles, porque la mayoría de los bugs aparecen por la interacción de dos factores.',
        'Un buen caso de prueba tiene un identificador, un título claro, precondiciones, datos, pasos, resultado esperado y trazabilidad al requisito. Tiene que poder ejecutarlo otra persona sin preguntarte nada. El testing exploratorio complementa a los casos escritos: aprendés, diseñás y ejecutás a la vez, guiado por un charter con un objetivo y un tiempo acotado, y anotás lo que encontrás.',
        'En la entrevista, ante "¿cómo probarías esto?", no arranques tirando casos al azar. Preguntá por los requisitos, separá funcional de no funcional, aplicá técnicas, cubrí camino feliz, errores, bordes, permisos y estados, y priorizá por riesgo. Esa estructura es lo que diferencia a un candidato fuerte.',
      ],
      checklist: [
        'Aplicar particiones de equivalencia y valores límite a un campo',
        'Armar una tabla de decisión para una regla de negocio',
        'Modelar los estados de un objeto y sus transiciones inválidas',
        'Explicar qué resuelve pairwise',
        'Escribir un caso de prueba completo y ejecutable por otra persona',
        'Planificar una sesión de testing exploratorio con un charter',
      ],
    },
    {
      id: 'bugs',
      title: 'Bugs: reportar, priorizar y analizar',
      body: [
        'Un buen reporte de bug tiene un título que describe el problema, entorno (versión, navegador, dispositivo, ambiente), pasos para reproducir, resultado esperado, resultado obtenido, evidencia (capturas, video, logs, request y response), severidad y prioridad. Tiene que permitir que un desarrollador lo reproduzca sin hablar con vos. Un reporte vago cuesta horas de ida y vuelta.',
        'Severidad es el impacto técnico; prioridad es la urgencia de negocio. Sabé dar ejemplos de cada combinación: el checkout que falla para todos es alta y alta; un error tipográfico en el logo de la home es baja severidad y alta prioridad; un crash en una pantalla de administración que nadie usa puede ser alta severidad y baja prioridad. El ciclo de vida típico es nuevo, asignado, en progreso, resuelto, verificado y cerrado, con reabierto, duplicado y rechazado como desvíos.',
        'Con un bug que no podés reproducir de forma consistente, buscá el patrón: datos, timing, concurrencia, caché, entorno, sesión. Revisá logs y métricas, anotá cada intento con sus condiciones y reportalo igual con la frecuencia observada y toda la evidencia. Nunca lo descartes solo porque no lo reproducís en tu máquina.',
        'En senior se espera análisis de causa raíz de los defectos que llegan a producción: por qué se introdujo, por qué no se detectó antes y qué cambio de proceso evita la familia completa de bugs, no solo ese. Herramientas como los cinco porqués sirven si terminan en acciones concretas y sin buscar culpables.',
      ],
      checklist: [
        'Escribir un reporte de bug reproducible con evidencia',
        'Dar un ejemplo de cada combinación de severidad y prioridad',
        'Describir el ciclo de vida de un defecto',
        'Explicar cómo encarás un bug intermitente',
        'Hacer un análisis de causa raíz de un bug escapado a producción',
      ],
    },
    {
      id: 'apis-y-plataformas',
      title: 'APIs, datos y plataformas',
      body: [
        'Probar APIs es central incluso en roles manuales. Con Postman o similar armás requests, usás variables de entorno, encadenás llamadas (por ejemplo, guardar el token del login) y escribís aserciones sobre status, body y headers. Sabé los códigos: `201` al crear, `400` por datos inválidos, `401` sin autenticación, `403` sin permisos, `404` si no existe, `409` por conflicto y `5xx` cuando falla el servidor. En un `POST /users` probá validaciones, duplicados, campos extra, tipos incorrectos, límites, autorización e idempotencia.',
        'SQL te permite preparar datos de prueba, verificar que una acción en la UI guardó lo correcto y validar migraciones: contar registros antes y después, buscar nulos donde no debería haberlos, huérfanos con `LEFT JOIN` y duplicados con `GROUP BY ... HAVING COUNT(*) > 1`. Con datos sensibles, usá datos sintéticos o anonimizados, nunca copias crudas de producción.',
        'En accesibilidad, una revisión manual incluye navegar solo con teclado (orden de foco, foco visible, sin trampas), probar con un lector de pantalla, revisar contraste, textos alternativos, etiquetas de formularios y zoom al 200%, usando WCAG como referencia. En usabilidad, mirás si el usuario entiende qué hacer, recibe feedback y se recupera de errores.',
        'En mobile sumás interrupciones (llamadas, notificaciones), cambios de red y modo avión, rotación, permisos, distintos tamaños y versiones de sistema operativo, batería y actualizaciones de la app. Para elegir navegadores y dispositivos, usá los datos de analytics de los usuarios reales y el riesgo, no una lista genérica.',
      ],
      checklist: [
        'Probar un endpoint con Postman con variables y aserciones',
        'Explicar los códigos de estado más comunes con un caso de cada uno',
        'Listar casos para un `POST /users` más allá del camino feliz',
        'Verificar con SQL la integridad de datos después de una migración',
        'Hacer una revisión manual de accesibilidad de una pantalla',
        'Elegir navegadores y dispositivos a partir de datos reales',
      ],
    },
    {
      id: 'estrategia',
      title: 'Proceso y estrategia de calidad',
      body: [
        'En un equipo ágil, QA participa desde el refinamiento: hace preguntas, detecta ambigüedades y ayuda a escribir criterios de aceptación en Given/When/Then. BDD aporta conversación compartida entre negocio, desarrollo y QA sobre ejemplos concretos; Gherkin es solo la sintaxis. Shift-left es mover la calidad antes (revisar requisitos, tests unitarios, análisis estático) y shift-right es aprender en producción (monitoreo, feature flags, canary releases), y se complementan.',
        'Un plan de pruebas define alcance, fuera de alcance, enfoque, entornos, datos, riesgos, criterios de entrada y salida, y responsables. La matriz de trazabilidad conecta requisitos con casos y defectos para ver qué quedó sin cubrir. Cuando hay poco tiempo, priorizá por riesgo: impacto en el usuario y el negocio por probabilidad de falla, y comunicá qué quedó sin probar.',
        'En senior te van a pedir estrategia: pirámide de testing y cuándo desviarte, quality gates en el pipeline (tests, cobertura de lo nuevo, análisis estático, seguridad), métricas útiles (defectos escapados, tiempo de detección y de corrección, tasa de flaky, change failure rate) y métricas a evitar (cantidad de casos o de bugs reportados por persona). También cómo incorporar performance, seguridad y accesibilidad sin un equipo dedicado.',
        'Los escenarios difíciles también se preguntan: salir a producción con bugs conocidos (informar el riesgo con datos, proponer mitigaciones y dejar la decisión explícita en quien corresponde), calidad con deploys continuos, microservicios con tests de contrato, un sistema legacy sin tests (empezar por tests de caracterización de los flujos críticos) y cómo armar QA en una organización que no lo tiene. La cultura de calidad se construye haciendo que el equipo sea dueño de ella, no siendo el último filtro.',
      ],
      checklist: [
        'Escribir criterios de aceptación en Given/When/Then',
        'Explicar shift-left y shift-right con prácticas concretas',
        'Armar un plan de pruebas y una priorización por riesgo',
        'Definir quality gates para un pipeline',
        'Proponer métricas de calidad útiles y explicar cuáles evitar',
        'Manejar la presión de salir con bugs conocidos',
        'Diseñar una estrategia de calidad para una organización sin QA',
      ],
    },
    {
      id: 'automatizacion',
      title: 'Automatización de pruebas',
      body: [
        'La pirámide de testing propone muchos tests unitarios (rápidos y baratos), menos de integración y pocos E2E (lentos y frágiles, pero cercanos al usuario). Automatizá lo repetitivo, estable y de alto riesgo: regresión de flujos críticos, smoke, APIs y combinaciones de datos. Lo exploratorio, la usabilidad y lo que cambia todo el tiempo siguen siendo manuales. El ROI se justifica en tiempo de regresión ahorrado, defectos detectados antes y frecuencia de release.',
        'Un buen test automatizado es independiente, determinístico, prueba una cosa y tiene un nombre que describe el comportamiento. Usá selectores estables y orientados al usuario (rol, label, texto o un `data-testid`), no clases CSS ni XPath frágiles. Una buena aserción verifica el resultado que importa al usuario, con un mensaje claro cuando falla. Cada test crea sus propios datos, idealmente por API, y no depende del orden de ejecución.',
        'Un flaky test pasa y falla sin cambios en el código. Las causas típicas son esperas fijas, dependencias entre tests, datos compartidos, animaciones, concurrencia y entornos inestables. Se encara midiendo la tasa de flakiness, poniendo en cuarentena los peores, arreglando la causa y no tapándola con reintentos. Page Object Model encapsula la interacción con cada pantalla para no repetir selectores; su riesgo es crecer hasta ser una capa enorme con lógica escondida.',
        'Mock, stub y fake son dobles de prueba: el stub devuelve respuestas fijas, el mock además verifica cómo se lo llamó y el fake es una implementación simplificada que funciona. En E2E se mockea para simular errores o servicios de terceros, sabiendo que perdés cobertura de la integración real. En CI, corré lo rápido en cada PR y lo pesado de forma programada, paralelizá, publicá reportes con trazas y screenshots. Los tests de contrato (por ejemplo con Pact) verifican que proveedor y consumidor de una API sigan de acuerdo sin levantar todo el sistema.',
      ],
      checklist: [
        'Explicar la pirámide de testing y qué automatizarías primero',
        'Elegir un selector robusto y justificarlo',
        'Diagnosticar y arreglar un flaky test',
        'Manejar datos de prueba para que los tests sean independientes',
        'Diferenciar mock, stub y fake',
        'Proponer cómo acelerar una suite E2E de 90 minutos',
        'Explicar qué son los tests de contrato',
      ],
    },
    {
      id: 'cypress',
      title: 'Cypress',
      body: [
        'Cypress corre los tests dentro del navegador, junto a la aplicación, lo que le da acceso directo al DOM, a la red y a una gran experiencia de debugging con time travel. A diferencia de Selenium, no usa WebDriver. Un test usa `describe` e `it`, visita una página con `cy.visit()`, encuentra elementos con `cy.get()` (por selector) o `cy.contains()` (por texto) y verifica con `.should()`. `cypress open` abre la interfaz interactiva para desarrollar y `cypress run` corre headless para CI.',
        'Los comandos de Cypress no son promesas: se encolan y se ejecutan en orden, por eso no se usa `async/await` y los valores se obtienen con `.then()` o aliases. Las queries como `get`, `find` y `contains` se reintentan junto con la aserción siguiente hasta que pasa o vence el timeout; las acciones como `click` o `type` no se reintentan. Por eso casi nunca hace falta `cy.wait(2000)`: si esperás una request, usá `cy.intercept()` con un alias y `cy.wait("@alias")`.',
        '`cy.intercept()` sirve para esperar, espiar o mockear requests, por ejemplo para simular un error 500. Las fixtures son archivos de datos que usás como respuestas o inputs. Los custom commands encapsulan acciones repetidas como el login, y `cy.session()` cachea cookies y storage de la sesión entre tests para no loguearse por la UI cada vez. `cy.task()` ejecuta código en Node, útil para preparar la base de datos o leer archivos. Los entornos se configuran en `cypress.config` y con variables de entorno.',
        'Sabé sus limitaciones: una sola pestaña, soporte de multi-dominio con `cy.origin()`, WebKit solo experimental y sin múltiples navegadores en el mismo test. Para paralelizar en CI se reparten specs entre máquinas, con Cypress Cloud o con un plugin de split. El component testing monta componentes aislados y es más rápido que E2E para lógica de UI. Malas prácticas comunes: esperas fijas, selectores frágiles, tests que dependen de otros, login por UI en cada test y aserciones sobre detalles de implementación.',
      ],
      checklist: [
        'Escribir un test de login con selectores estables y aserciones',
        'Explicar por qué los comandos no son promesas',
        'Explicar qué comandos se reintentan y cuáles no',
        'Mockear y esperar una request con `cy.intercept()`',
        'Usar `cy.session()` y custom commands para el login',
        'Nombrar las limitaciones de Cypress y cómo sortearlas',
      ],
    },
    {
      id: 'playwright',
      title: 'Playwright',
      body: [
        'Playwright controla Chromium, Firefox y WebKit con una sola API, soporta varias pestañas, dominios y contextos, y trae un test runner con paralelismo, fixtures, reportes y trace viewer. Los locators son la forma recomendada de encontrar elementos: `page.getByRole()`, `getByLabel()` y `getByText()` se parecen a cómo el usuario percibe la página y resisten cambios de CSS. Los locators son perezosos: se resuelven al momento de actuar.',
        'El auto-waiting espera a que el elemento esté visible, habilitado y estable antes de cada acción. Las web-first assertions como `await expect(locator).toBeVisible()` se reintentan hasta el timeout, mientras que `expect(await locator.isVisible()).toBe(true)` evalúa una sola vez y genera flakiness. `browser` es la instancia del navegador, `context` es una sesión aislada (cookies, storage) y `page` es una pestaña; cada test recibe un context nuevo.',
        'Para no loguearte por la UI en cada test, usá un setup project que haga login una vez y guarde el `storageState`, y que los demás projects lo reutilicen. Los fixtures inyectan dependencias en los tests (page objects, usuarios, datos) con setup y teardown. Con `page.route()` interceptás y mockeás respuestas, y con el fixture `request` hacés tests de API o preparás datos. Los projects en `playwright.config.ts` permiten correr la suite en varios navegadores, dispositivos o configuraciones.',
        'Para investigar fallas en CI, configurá `trace: "on-first-retry"` y abrí el trace con DOM, red, consola y screenshots de cada paso. Escalá con workers en paralelo y `--shard` entre máquinas, uniendo los reportes con `merge-reports`. Visual regression con `toHaveScreenshot()` necesita un entorno de render fijo (por ejemplo, un contenedor), enmascarar contenido dinámico y un proceso para aprobar cambios. Frente a Cypress, Playwright gana en multi-navegador, multi-pestaña y paralelismo nativo; Cypress tiene una experiencia interactiva muy pulida y un component testing maduro.',
      ],
      checklist: [
        'Escribir un test con `getByRole()` y web-first assertions',
        'Explicar `browser`, `context` y `page`',
        'Reutilizar la sesión con `storageState` y un setup project',
        'Crear un fixture propio',
        'Mockear una API con `page.route()` y hacer un test de API con `request`',
        'Investigar una falla de CI con el trace viewer',
        'Comparar Playwright y Cypress con criterio',
      ],
    },
    {
      id: 'k6',
      title: 'Performance con k6',
      body: [
        'Antes de la herramienta, sabé los tipos de prueba: smoke (carga mínima para validar el script), carga (tráfico esperado), estrés (más allá de lo esperado, para encontrar el punto de quiebre), spike (subida brusca), soak (carga sostenida por horas para encontrar leaks) y breakpoint. Cada una responde una pregunta distinta, y la estrategia empieza por definir objetivos de negocio: usuarios, transacciones por segundo y SLOs de latencia y errores.',
        'k6 usa scripts en JavaScript (y TypeScript desde la versión 1.0): exportás `options` con la configuración y una función por defecto que ejecuta cada virtual user (VU) en loop; cada pasada es una iteración. `check` verifica una condición sin cortar la prueba, mientras que los `thresholds` definen criterios de éxito sobre métricas agregadas (por ejemplo `http_req_duration: ["p(95)<500"]`) y hacen fallar la ejecución, lo que los vuelve clave para CI. Se usa el p95 en vez del promedio porque el promedio esconde la cola que sufren los usuarios.',
        '`sleep` simula el tiempo de pensamiento del usuario. `setup` corre una vez antes (por ejemplo, obtener un token) y `teardown` una vez al final. Los scenarios definen distintos patrones de carga con executors: `ramping-vus` y `constant-vus` siguen un modelo cerrado (la carga depende de cuánto tarda el sistema), mientras que `constant-arrival-rate` y `ramping-arrival-rate` siguen un modelo abierto (llegan N iteraciones por segundo sin importar la respuesta), que refleja mejor el tráfico real y evita la coordinated omission.',
        'Para datos, usá `SharedArray` para cargar un CSV o JSON una vez y compartirlo entre VUs. La correlación es extraer valores dinámicos de una respuesta (un token, un id) y usarlos en la siguiente request. Para dimensionar VUs con arrival rate, usá la ley de Little: VUs igual a tasa por duración de iteración; 200 iteraciones por segundo de 1,5 segundos piden unos 300 VUs, más margen en `preAllocatedVUs`. Analizá resultados exportando a Prometheus, InfluxDB o Grafana, correlacionando con métricas del servidor, y reportá contra los objetivos en un entorno representativo de producción.',
      ],
      checklist: [
        'Diferenciar pruebas de carga, estrés, spike, soak y smoke',
        'Escribir un script de k6 con `options`, checks y thresholds',
        'Explicar por qué se usa p95 y no el promedio',
        'Elegir entre modelo abierto y cerrado y su executor',
        'Dimensionar VUs para un arrival rate dado',
        'Integrar k6 en CI con thresholds que corten el pipeline',
        'Explicar coordinated omission',
      ],
    },
    {
      id: 'ejercicios',
      title: 'Ejercicios prácticos',
      body: [
        'El ejercicio más común en QA manual es diseñar casos en vivo: un login, un formulario de registro, un carrito, un campo de fecha, un ascensor o una máquina expendedora. Empezá preguntando requisitos y supuestos, después organizá por categorías (funcional, validaciones, bordes, seguridad, usabilidad, accesibilidad, performance, compatibilidad) y aplicá técnicas explícitamente. Cerrá priorizando: si tuvieras diez minutos, ¿qué probarías primero?',
        'Otro ejercicio frecuente es encontrar bugs en una app de demo y reportarlos. Ahí se evalúa tanto lo que encontrás como la calidad del reporte: pasos claros, esperado contra obtenido, evidencia y severidad bien justificada. Practicá con apps de prueba públicas y con los productos que usás todos los días.',
        'En automatización suelen pedirte automatizar un flujo (login y compra, búsqueda y filtro) con la herramienta del equipo, en vivo o como take-home. Mostrá estructura (page objects o helpers simples), selectores robustos, aserciones significativas, datos independientes, sin esperas fijas, y un README con cómo correrlo y qué dejarías para después. También pueden darte un test flaky o mal escrito para que lo revises.',
        'Si el rol incluye performance, el ejercicio típico es escribir un script de k6 para un endpoint con un escenario y thresholds, o interpretar un resultado y decir dónde está el cuello de botella. Practicá cada tipo de ejercicio con tiempo limitado y en voz alta.',
      ],
      checklist: [
        'Diseñar casos para un formulario de registro en 15 minutos con técnicas explícitas',
        'Encontrar y reportar tres bugs en una app de demo',
        'Automatizar un flujo de login y compra con buenas prácticas',
        'Revisar un test mal escrito y proponer mejoras',
        'Escribir un script de k6 con escenario y thresholds',
      ],
    },
    {
      id: 'dia-de-la-entrevista',
      title: 'El día de la entrevista',
      body: [
        'Pensá en voz alta: en QA lo que se evalúa es tu forma de pensar sobre el riesgo. Hacé preguntas de aclaración antes de diseñar casos (quiénes son los usuarios, qué reglas de negocio hay, qué plataformas) y explicitá tus supuestos. Si no conocés una herramienta o un concepto, decilo y contá cómo lo aprenderías o con qué lo resolvés hoy.',
        'Para preguntas de comportamiento usá STAR: situación, tarea, acción y resultado. Prepará historias sobre un bug crítico que encontraste, un desacuerdo con un desarrollador sobre la severidad de un bug, una vez que tuviste que priorizar con poco tiempo, una mejora de proceso que propusiste y un bug que se te escapó a producción y qué aprendiste.',
        'Preguntas para la empresa: cómo es la relación entre QA y desarrollo, cuánto está automatizado y quién mantiene los tests, cómo es el pipeline de CI, qué pasa cuando hay bugs conocidos antes de un release, cómo miden la calidad y qué herramientas usan para gestión de casos y bugs.',
        'Checklist final: repasá las técnicas de diseño con un ejemplo cada una, tené listo un ejemplo de reporte de bug, si hay código en vivo dejá el entorno instalado y probado con la herramienta que usan, y llevá un proyecto de automatización propio en un repo para mostrar.',
      ],
      checklist: [
        'Hacer preguntas de aclaración antes de diseñar casos',
        'Admitir lo que no sabés y explicar cómo lo aprenderías',
        'Tener cuatro historias STAR preparadas',
        'Llevar preguntas sobre proceso, automatización y cultura de calidad',
        'Tener el entorno de automatización instalado y un repo propio para mostrar',
      ],
    },
  ],
};
